### ISSUE TITLE
Implement duration bar for Miner and Forager

### ISSUE THREAD

**Issue by HaroldHS** [UQdeco2800/2022-studio-3#100]
# **Description**
**Task:** [Implement duration bar for Miner and Forager](#100).
**Feature:** [Team 8 - Sprint 2 - Friendly Worker Units Continued](#98)
Implement a duration bar for mining stone & metal (for Miner) and wood (for Forager). The duration bar made by creating an animation, a bar above workers when the resource collided with the worker such as Miner and Forager.
  
## **Example**
- **Mining duration**: Duration will be visualized by creating a bar above resources

# **Dependencies**
For this task, there are 3 dependencies to be considered.

- [x] Map, resources (#3)
- [x] Miner class / MinerFactory (#23)
- [x] Forager class / ForagerFactory (#22)
 
# **Milestones**
- [x] Creating duration bar entity (Sept. 8)
- [x] Attach the duration bar above Miner & Forager (Sept. 9)
 
**Completion Deadline:** Sept. 10
 
# **Documentation**
Wiki page detailing on how the duration bar works
 
# **Member**
- Lorenzo (@lorenzopolicar) (Lorenzo Policar)
- Harold (@HaroldHS) (Harold Hotma Sibuea)
- Wishnu (@hazlazuardi) (Wishnu Hazmi Lazuardi)
- Yash (@yashvardhanbatra) (Yashvardhan Batra)
