### ISSUE TITLE
Sprites for Miner and Forager

### ISSUE THREAD

**Issue by HaroldHS** [UQdeco2800/2022-studio-3#101]
# **Description**
**Task:** Sprites for Miner and Forager(#101 ).
**Feature:** [Feature which this tasks contributes to implementing](#98)
Each worker unit has its own design (sprites) and animation. 

# **Dependencies**
This task require Miner class / MinerFactory and Forager class / ForagerFactory to be done in order to add the sprites/animation as the component for the MinerFactory and ForagerFactory.

- [x] Miner class / MinerFactory (#23)
- [x] Forager class / ForagerFactory (#22)
 
# **Milestones**
- [x] Creating sprites for Miner (Sept. 8)
- [x] Creating sprites for Forager (Sept. 9)
 
**Completion Deadline:** Sept. 10
 
# **Documentation**
Wiki page about the design of each worker unit type.
 
# **Member**
- Lorenzo (@lorenzopolicar) (Lorenzo Policar)
- Harold (@HaroldHS) (Harold Hotma Sibuea)
- Wishnu (@hazlazuardi) (Wishnu Hazmi Lazuardi)
- Yash (@yashvardhanbatra) (Yashvardhan Batra)
