### ISSUE TITLE
Team 5 - Sprint 2 - Advanced Dialogue Box

### ISSUE THREAD

**Issue by usrnatc** [UQdeco2800/2022-studio-3#103]
# **Description**
**Dialogue Box Functionality:** Refining and increasing robustness of Dialogue Box functionality
**Feature:** [Advanced Dynamic/Static UI](#87)

Dialogue box will be mutable in all aspects but the overall sizing/positioning `on-the-fly`.
Dialogue box dismiss functionality to work whenever it is called.

# **Examples**
 - **On-the-fly Mutability**: dialogue box content and style will be able to be altered whilst the dialogue box is showing
 - **Dismiss Robustness**: ensure dismiss functionality through rigorous testing
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] allow mutable image (week 6)
- [ ] ~~allow mutable skin (week 6)~~
- [x] allow mutable title/text (week 6)
- [x] dismiss functionality tests (week 6)
 
**Completion Deadline:** Monday (week 7)
 
# **Member**
- Nathan Corcoran (@usrnatc) Nathan

**Comment by usrnatc** [comment]
Dialogue Box skin was not made mutable so as to conform to the over-arching game aesthetic
