### ISSUE TITLE
Team-3 Sprint 1_Feature_Ticket_Sound_and_BGMs

### ISSUE THREAD

**Issue by prathammanocha** [UQdeco2800/2022-studio-3#11]
# **Description**
We're going to work on the sounds and effects part of the game. Music is a tool that may be used to manage emotions and set the tone of a narrative. Instead of simply observing what happens, you are directing the activities of a character. Therefore, having a soundtrack that can set a mood and genuinely engage the player is essential for video game developers. We're going to use tools like Audacity and Garageband. Garageband would specifically be used for creating original bits of sounds ourselves and Audacity would be used for editing and putting together the music.

## SubFeature/component
* Helping in the integration of sound options (Toggling music sound, Variation with in-game music)
* Menu log sound effect, intro music theme
* Character Interaction sound effect
* Integrating music to code, synchronising music with character action and gameplay theme and transitioning

## **Examples**
* Calm music playing when the game is launched. 
* When a boss enters or enemies are detected, the music turns dramatic, indicating the same.
* Generally, the music is focused on the story and its progression.
* Sound effects include sounds such as the player walking, enemy approaching, underwater sounds, etc.

## **Dependencies:**
* Sound effects : depend on unit creating teams(unit sound effects), events generating teams(transitioning sound effects)
* Music settings : depend on team 5 who make the main menu
* Music : events generating teams(background music based on the process of story)

# **Milestones**
- [ ] Goal 1: Decide on music for intro, menu interaction sounds (15 Aug)
- [ ] Goal 2: Working on theme music and transitioning sound effect each game stages (18 Aug)
- [ ] Goal 3: Compose character interaction sound effect (22 Aug)
- [ ] Goal 4: Integrating sound effect to code base, synchronising with transitioning and character interaction(28 Aug)
- [ ] Finalize: 29 Aug (Sprint 1 Due date)

**Completion Deadline:** Aug. 30

# **Members**
- Pratham Manocha (@prathammanocha)
- Yashvardhan Batra (@yashvardhanbatra)
- Hoang Viet (@nhVietS)
- Xinrui Tan (@Xanadu-james)

**Comment by Jonoym** [comment]
Adding what your feature is to the title of the ticket would be great

**Comment by nhVietS** [comment]
Team 3 dispensed
