### ISSUE TITLE
Team 2 Sprint 2 Ticket

### ISSUE THREAD

**Issue by syl2211** [UQdeco2800/2022-studio-3#112]
# **Description**
**Task:** [Barracks Redesign Level 2 and Level 2](#3).
**Feature:** [Team 2 Sprint 2 Advanced Buildings](#2)

Redesign the barracks designs and have a level one and two design. Also have transitional designs for barracks level up animation. These designs will have to be consistent with the town hall and the mines design. The redesign will need include documentation in the wiki as well.
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Barracks Level 1 Redesign (Sep. 3)
- [ ] Barracks Level 2 Design  (Sep. 5)
- [ ] Barracks Level 1 to 2 Transition for barracks animation (Sep. 8)
 
**Completion Deadline:** Sep. 12
 
# **Documentation**
- [Update information for barracks style](../wiki/Buildings-Style)
- [Update barracks image](../wiki/Buildings-Attribute-List)
 
# **Member**
- Sylvia (@syl2211)
