### ISSUE TITLE
Base building UI

### ISSUE THREAD

**Issue by Spooey** [UQdeco2800/2022-studio-3#117]
# **Description**
**Task:** [Building UI](#3).
**Feature:** [Team 2 Sprint 2 Advanced Buildings](#99 )

B basic building UI will be implemented on all buildings which all have a shared functionality. The UI will display the current selected building and interactable buttons for leveling up.
 
# **Dependencies**
- [ ] Building level up designs will need to be completed

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1 (Sep. 6) building will display as being selected
- [ ] Step 2 (Sep. 8): building will have interactable components which will have some affect on the building
 
**Completion Deadline:** Sep. 9

 
# **Documentation**
- [Information Box building selection](https://github.com/UQdeco2800/2022-studio-3/wiki/Unit-Selection-%26-Information-Box/_edit)

 
# **Member**
- Angus Buchanan (@Spooey)
