### ISSUE TITLE
Team 2 Sprint 2 --- Two Levels of Mining Camp Design

### ISSUE THREAD

**Issue by nicococole** [UQdeco2800/2022-studio-3#119]
# **Description**
**Task: Mining Camp level one and level two.
**Feature:**  Team 2 Sprint 2 Advanced Building

Based on the new desgin of town hall and barrack and the request of lmitation of color and size, redesign the design of mining camp with level one and level two. These two design have to be consistent with the design of tonw hall and barrack. 
# **Milestones**
List of steps that need to be completed for this task.
- [x] new sketch for mining camp (September 01).
- [x] level one sketch design of mining camp (September 5).
- [x]  level two sketch design of mining camp (September 6).
- [x] level one end design of mining camp (September 08).
- [x] level two end design of mining camp (September 08).
 
# **Documentation**
- [Update information for mining camp style](https://github.com/UQdeco2800/2022-studio-3/wiki/Buildings-Style)
- [Update image of building attribute of mining camp](https://github.com/UQdeco2800/2022-studio-3/wiki/Buildings-Style)
 
# **Member**
- Wenjing Shan (@nicococole )(wenjing)
