### ISSUE TITLE
Team 4 - Sprint 1 - Enemy Units

### ISSUE THREAD

**Issue by Abishtu** [UQdeco2800/2022-studio-3#12]
# **Description**
This ticket deals with the graphics, including sprites and animations, and internal mechanics of 
enemy units, which includes movement, enemy stats such as enemy health, enemy level, enemy mana levels etc., 
and enemy combat. Unlike friendly units, enemy units will be fully controlled by the AI, so we are goin to
develop basic AI behaviours in this first sprint.

This should be roughly a one paragraph description of the features / ideas on which your team plans to work. 
It should very briefly touch on why you think it should be in the game (e.g. "Adds an extra layer of depth 
to game play"). It should also describe how it will appear or be used in the final product (e.g. "On starting a level, the game will generate a random, procedurally-generated map").

## SubFeature/component (optional)
- AI controls unit movement and combat
- Unit generation will depend on story/game events and/or through specific
locations such as enemy camps or random encounters in the forests.
- Unit designs will follow the general Atlantian oceanic theme however they
will be a bit more diverse than the friendly units, so more different looking
demons and deep sea creatures.
  - This is to communicate the fact that the enemy units are evil and 
  chaotic creatures.
- Initial Unit Types:
  - Ghouls: akin to light infantry units, they are small and have basic 
  close range melee attack
  - Demon: akin to heavy infantry units, they are big and use heavy maces to attack
- Units should have some stats, such as health, level, attack and defence modifiers,
speed.

# **Dependencies**
- Unit generation/deployment will require map to be developed (see #3).
- I guess we'll need some friendly units made to test if auto attack works 
(see #8)
- UI elements to show health bar and location of enemies on the map.
- Sound effects for units.

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Implementing unit entities, including its config files/classes and factory methods (Aug. 23)
- [x] Sprites and Animations  (Aug. 23)
- [x] Unit generation (Aug. 28)

**Completion Deadline:** Aug. 30

# **Extras (optional)**
- [x] Projectile for ranged units.
- [x] Large ship units.

# **Documentation**
- [Units listing and characteristics](../wiki/Units-Home)

# **Members**
- Harikesha Suresh (@Abishtu)
- Yiliang Xu (@Lucas-XU99)
- Xibin Wang (@ooo09)
- Jun Utsunomiya (@JunUtsunomiya)
- Zhiyuan Xu (@DLAmeng)
