### ISSUE TITLE
Team 5- Sprint 2 - Cutscenes

### ISSUE THREAD

**Issue by yobicakes** [UQdeco2800/2022-studio-3#126]
# **Description**
**Task:** [Cutscenes](#3)
**Feature:** [Static/Dynamic UI](#2)
The cutscenes facilitate the user's introduction to the game story. They will consist of dynamic images with static text involving the story line. The user may select "next" or "skip" depending on their status. The cutscenes will also play basic sound.
 
## **Example**
- **Cutscene initialisation**: A user clicks on "start" and is immediately taken to the cutscenes. The user reads the cutscene and clicks on "next" until they have read all the cutscenes. Finally, they click on "start". A recurring user who knows the story has the option to click "skip" to start the game immediately. 

# **Dependencies**
The cutscenes' story had to be established through the design commitee's story team. Additionally, basic sound was required via the Sound Team (not officially established in our studio). 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Cutscene Designs (Sep. 10)
- [x] Cutscene Initialisation via code (Sep. 10)
- [x] Cutscene "skip" and "next" buttons (Sep. 10)
- [x] Basic sound playability (Sep. 10)

 
**Completion Deadline:** Sep. 12 

 
# **Member**
- Neha (@yobicakes )(Neha Tewari)
- Tyrion (@Suuoooooooo ) (Tiansong Zhang)
