### ISSUE TITLE
Team-8 Abstract Worker Unit Class

### ISSUE THREAD

**Issue by KungKemi** [UQdeco2800/2022-studio-3#13]
# **Description**
**Task:** [Abstract Worker Unit Class](#3)
**Feature:** [Friendly Units (Workers)](#5)

We will implement an abstract `Worker` class which represents a general worker unit.

A worker unit should have the following properties:

1. **Health** -  each worker unit will have a set health upon spawning which will deplete when they are damaged by an enemy unit. When a worker unit's health bar drops to (or below) zero, then they die and de-spawn.
2. **Hitbox** - the worker unit's sprite will be surrounded by a region in which they can be selected, and take damage from enemies.
3. **Movement speed** - the time taken for a worker unit to travel a given distance should be fixed and specific to each unit type. The movement speed may vary based on where the unit is moving (i.e., faster over land than through water).
4. **Inventory** - a worker unit should be capable of holding resources which they have gathered. There should be a restriction on the amount of each resource a given unit can carry at a time.
5. **Interactable objects** - a list of objects on the map which the worker unit can interact with.
6. **Task queue** - a queue for tasks which the worker unit performs in order. The player should be able to assign new tasks to a worker unit, or else tell a unit to halt their current task and start on a new one.
 
## **Examples**
- **Inventory**: a miner unit may be only able to carry 10 stone and 5 iron at a time, and must deposit said recourses before being able to gather more.
- **Interactable objects**: a forager unit may be able to gather wood from bushes, while a miner unit cannot interact with bushes.
- **Task queue**: if a player tells a forager unit to collect resources from an interactable object, the unit would queue up a task to move to said location; a task to collect resources until their inventory is full; a task to return home; a task to deposit resources; etc.

# **Dependencies**
- [ ] The task queue depends on tasks implemented as part of the task system
- [ ] The interactable objects depend on objects generated on the map
- [ ] The inventory depends on the resources implemented as part of the game
- [ ] The damage taken by worker units depends on the implemented damage system
 
# **Milestones**
- [ ] Implemented non-task queue aspects of `Worker` class (Saturday, Week 5)
- [ ] Finished initial testing of `Worker` class (Sunday, Week 5)
- [ ] Added task queue to `Worker` class (Tuesday, Week 5)
- [ ] Finished final tests for `Worker` class (Wednesday, Week 5)
 
**Completion Deadline:** Wednesday, Week 5 (August 25th)
 
# **Documentation**
- A wiki page detailing the `Worker` class will be created
- A javadoc detailing the `Worker` class will be created
 
# **Members**
- Thomas (@thomas-keevers) (Thomas Keevers)
- Alex (@KungKemi) (Alexander Johnson)
