### ISSUE TITLE
Creation of menus for spawning units and buildings (plus upgrades), visualizing costs 

### ISSUE THREAD

**Issue by Mehr-creates** [UQdeco2800/2022-studio-3#140]

**Comment by HJPearce** [comment]
# **Description**
**Task:** [Spawning menu creation](#140).
**Feature:** [Initial economy](#139)

The building menus and global level menu need to be extended with buttons for producing each of their respective units and buildings. Each of these buttons should include the title of what is to be produced, the cost of the item in terms of wood, stone and metal, and an icon visually representing the construction.  
Buttons will be darkened when they are not available to be selected
Production of units should count towards the unit cap, and you should not be able to produce units when the cap is reached.
 
## **Example (optional)**
- **Town hall**: The town hall is able to produce workers and spearmen. The workers cost 4 wood, and the spearmen cost 6 wood.
- **Buildings**: Barracks, Walls and Camps are all available to be built and must have their respective costs

# **Dependencies**

The functionality of producing a building depends on #141 and #143.  
Unit placement requires some algorithm to check for space that is not yet implemented

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Icon Assets need to be added
- [ ] Menu widget needs to be created
- [ ] Unit menus need to be attached to whether the appropriate building is selected
 
**Completion Deadline:** Sep 20

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- e.g. Richard (@AppleByter) (Richard Thomas)

**Comment by HJPearce** [comment]
This is handled in spawning menu creation continuation, and unit menus have been taken on as a responsibility by team 6
