### ISSUE TITLE
Cooldowns for spawning 

### ISSUE THREAD

**Issue by Mehr-creates** [UQdeco2800/2022-studio-3#142]
# **Description**
**Task:** This enables a cooling interval to be supplied to the user when the units are spawned, preventing further unit spawning for a brief period of time.
**Feature:** This contributes to a waiting period, which does not allow the user to spawn more units if they have been recently produced. 

## **Examples**
When a building is selected for spawning the building, there is a waiting period for the next spawning to occur. When the bar is complete the user can then spawn more troops (or units)

# **Dependencies**
This task is dependent on the buildings generated by team 2 #112
And possibly the troop generation of friendly units. 
 
The task includes:
- [x] Determining the time duration for the time when the last spawning occurred. 
- [ ] Disabling spawning for a period of time. 
- [ ] Displaying cooldown periods

# **Documentation**

 
# **Member**

**Comment by nhVietS** [comment]
closed due to abandoned feature.
