### ISSUE TITLE
Team 7 - Sprint 3 - Enemy Unit Movement

### ISSUE THREAD

**Issue by jordanlbf** [UQdeco2800/2022-studio-3#145]
# **Description**
**Task:** Enemy Unit Movement
**Feature:** [Map Flooding and Enemy Movement](#2)

This task involves implementing a line of sight for enemy units and basic pathfinding for enemy units. Within this line of sight, enemies will be able to recognise friendly units and lock onto them to attack. When an enemy unit is not locked onto a target, it will undeterministically roam the map. Basic pathfinding will be implemented to help enemy units avoid nearby objects.
 
## **Example**
- When a friendly unit enters an enemies line of sight, the enemy will lock onto that unit.
- Basic pathfinding will help enemy units navigate objects.
 
# **Milestones**
- [ ] Step 1 (Sept. 22) - Provide enemy units with a line of sight.
- [ ] Step 2 (Sept. 26) - Have enemy units recognise objects and friendly units within there line of sight.
- [ ] Step 3 (Oct. 2) - Implement pathfinding to avoid obstacles for enemy units.
 
# **Member**
- Jordan (@jordanlbf) (jordanlbf )
- Fauzan Hanandito Chaidir (@Corfliss)
