### ISSUE TITLE
Team 7 - Sprint 3 - Map Flooding

### ISSUE THREAD

**Issue by Corfliss** [UQdeco2800/2022-studio-3#146]
# **Description**
**Task:** Map Flooding
**Feature:** [Map Flooding and Enemy Movement](#144)

Implementing the flooding system will make it stick to the lore of the game about flooding Atlantis. In order to implement that, this ticket will include the system on whether or not a terrain will be turned into a flooded terrain or not and when to do so.
 
## **Example (optional)**
* Grass terrain that is near the flooding will turn into sand, as the flooding progresses, and then will turn into the flooded terrain.
* If the adjacent diagonal terrain is flooded, it will turn into a sand on the next phase.
* If the adjacent horizontal or vertical terrain is flooded, it will also turn into flooded on the next phase.

# **Dependencies**
[Map Feature](#49)
 
# **Milestones**
- [ ]  Step 1: Implement the flooding timer.
- [ ] Step 2: Adding the flooding detection mechanics.
- [ ] Step 3: Making the transition from terrain to flooding to any terrain that is adjacent to water.
**Completion Deadline:** Oct. 03

# **Documentation**
* Documentation will be added later.
 
# **Member**
- Jordan Brewis Foulger (@jordanlbf)
- Fauzan Hanandito Chaidir (@Corfliss)
