### ISSUE TITLE
Team 4 - Sprint 3 - Buildings

### ISSUE THREAD

**Issue by Abishtu** [UQdeco2800/2022-studio-3#149]
# **Description**
This sprint we'll be making a variety of buildings, this includes enemy spawning buildings, and defensive buildings, we will also be working out additional refinements such as making visuals for building health.

## **Examples (optional)**

- Visualizing building health.
      - Changing sprite of building depending on remaining health
      - Proposed transitions:
           - 50% -- light damage, cracks and holes
           - 100% -- Rubble
- Enemy spawning buildings
      - Ships that transport enemies to shore
      - Ttian shrine, temple that slowly generates Titans, this has to be destroyed by players to stop titans from spawning
- Defensive buildings
       -  Trebuchet for coastal defense, attacks enemy transport ships
       - Multi-level:
            - Lvl 1 -- Simple wood and stone trebuchet, lower range
            - Lvl 2 -- Metal and stone trebuchet, better defense, range and attack
            - Lvl 3 -- Magic trebuchets!! They're magic so they'll be cool
- Design ideas
       - Ancient Greek architecture and temples, and Greek style ships with a dark twist
       - Skills, bones, carcasses and lots of blood (but not too much) for Titan spawn shrine.
       - Titan Shrine: When the building's health is reduced to 50% or less, the titan will be summoned at twice the original rate, similar feature will be extended to other buildings.

# **Dependencies**

- Redesigning/Resizing enemy units. 

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Titan Shrine Design (Sep. 23)
- [x] Ship design (Sep. 23)
- [x] Trebuchet Design (Lvl 1 and 2) (Sep. 23)
- [x] Damage sprites (Sep. 28)
- [x] Programming entities (Sep. 26)
- [x] Ranged Attack for trebuchet (Sep. 27)

**Completion Deadline:** Sep. 30

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- ...

# **Members**
- Harikesha Suresh (@Abishtu)
- Yiliang Xu (@Lucas-XU99)
- Xibin Wang (@ooo09)
- Jun Utsunomiya (@JunUtsunomiya)
- Zhiyuan Xu (@DLAmeng)
