### ISSUE TITLE
Team 6 Sprint 3: City design feature

### ISSUE THREAD

**Issue by kaitlyn-lake** [UQdeco2800/2022-studio-3#150]
# **Description**

This feature will focus on designing the buildings, layers and features of the island city. It will implement the visual component of the city and in later sprints gameplay functionality will be added. This design will allow the player to feel as if they are actually in Atlantis, and will provide a baseline for the final gameplay functionality and gameplay loop.

## SubFeature/component (optional)

- Implement a gate with a variable collider and opening/closing animation
- Procedural city generation
- Design city features: water feature, gardens, walls, paths, houses
- Generate a path between buildings

## **Examples (optional)**
-  Player loads into the game, the city is centred on and populated with buildings, pathways, walls and gates. The player may send friendly units through the city gates which will open for them, enemies may not pass.

# **Dependencies**

N/A

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Basic city textures and designs (Sep. 20)
- [x] Implement gate functionality (Sep. 20)
- [x] First pull request (Sep. 21)
- [x] Procedural city generation (Sep. 23)
- [x] City path generation (Sep. 24)
- [x] All city sub features merged and city displays (Sep. 24)
- [x] Last pull request (Sep. 25)

**Completion Deadline:** Sep. 25

# **Extras (optional)**
- [ ] Gameplay functionality of walls (can upgrade walls with resources so they are more resistant to attacks)

# **Documentation**

To be added.

# **Members**

Ryan Gibbons (sssss#2970)[ (rjg1](https://github.com/rjg1))
Kaitlyn Lake (@kaitlyn) ([kaitlyn-lake](https://github.com/kaitlyn-lake))
Fengqi Yu (@Fengqi Yu) ([Fengqi0822](https://github.com/Fengqi0822))
Max Jenkins (@Jenko)[ (MaxJenko](https://github.com/MaxJenko))
