### ISSUE TITLE
Procedural City Generation

### ISSUE THREAD

**Issue by rjg1** [UQdeco2800/2022-studio-3#151]
# **Description**
**Task:** [Procedural City Generation](#3).
**Feature:** [Feature which this tasks contributes to implementing](#2)
This task will implement the code necessary to dynamically place buildings within the city bounds and generate paths between them. It will be responsible for the aesthetic quality of the city and implement the building and placement of the city into the game on start.
 
## **Example (optional)**
- The user loads into a new game, the camera will be centred on the city, which contains a number of buildings that the player can interact with. Walls will spawn around the city, alongside gates, which will let friendly units exit, and block enemy units from entry.

# **Dependencies**

- [x] Building design (#xx)
- [ ] City features design (e.g water features) (#xx)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Create dynamic building placement (Sep 21)
- [x] "Pretty up" the city, by adding paths between buildings and features (Sep 23)
- [x] Visualise design in game (Sep 24)
 
**Completion Deadline:** Sep 26
 
# **Documentation**
- Wiki articles showing how to add buildings
- Wiki articles on the design of buildings/paths
 
# **Member**
- Ryan Gibbons (sssss#2970)[ (rjg1](https://github.com/rjg1))
- Kaitlyn Lake (Kaitlyn) ([kaitlyn-lake](https://github.com/kaitlyn-lake))
