### ISSUE TITLE
City gate

### ISSUE THREAD

**Issue by kaitlyn-lake** [UQdeco2800/2022-studio-3#152]
# **Description**
**Task:** [City gate](#3).
**Feature:** [Team 6 Sprint 3: City design feature](#150)

This task will implement a gate animation and functionality to the city walls. See **Example** for functionality description. It will require a design component that creates the artwork to be rendered and animated, and a programming component to render its functionality in game.
 
## **Example (optional)**
- **Gate opens**: A friendly unit approaches the gate and the animation of the gate opening is triggered. The unit is allowed entrance to the city. An enemy unit approaches and the gate remains closed and they are not allowed entrance.

# **Dependencies**

N/A
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create gate design and animation (Sep. 21)
- [x] Render gate in the city walls (Sep. 23)
- [x] Apply collider functionality to enemy and friendly units (Sep. 24)
- [x] Wiki documentation (Sep. 25)
- [ ] Unit testing (Sep. 25)
 
**Completion Deadline:** Sep. 25
 
# **Documentation**

To be added.
 
# **Member**

Ryan Gibbons (sssss#2970)[ (rjg1](https://github.com/rjg1))
Kaitlyn Lake (@kaitlyn) ([kaitlyn-lake](https://github.com/kaitlyn-lake))
