### ISSUE TITLE
Team 5 - Sprint 3 - Tutorial

### ISSUE THREAD

**Issue by alyshaziya** [UQdeco2800/2022-studio-3#153]
# **Description**
**Task:** [Tutorial](#3).
**Feature:** [Team 5 - New UI/Tutorial/Cutscenes](#148)

Implementing an interactive optional tutorial for the game to enhance playability. The feature will prompt the user to complete specific tasks (eg select troops, level up base, collect resources, train troops)  to teach players the key gameplay mechanics. 
This includes creating a new game screen (`TutorialGameScreen`) and using the `DialogueBox` and other features to create a simple static tutorial, and when all tasks are complete changing to a main game screen. For this sprint we will focus on creating a static version as many features are incomplete, and if time permits or features are complete we will integrate them into the tutorial.

## **Example (optional)**
- **Tutorial/Info**: RTS games are generally complicated with many features. Using a tutorial ensures that people unfamiliar with the genre are able to play the main game and have a higher chance of winning. People will also have the option to skip the tutorial if they choose to. 

# **Dependencies**
- Tutorial: Interactable features/gameplay being developed currently, but we will work around this by focusing on creating a static version.

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Create GitHub wiki of intended tasks and intended features to include in the tutorial, and finalise them
- [ ] Add dialogues and prompts for finalised tasks to GitHub wiki 
- [ ] Start building out a static version of the tutorial in a new screen (`TutorialGameScreen`)
- [ ] Add any completed features into the tutorial (optional)
- [ ] User Testing
 
**Completion Deadline:** Sept 3
 
# **Documentation**
- Will be added shortly 

# **Member**
- Nathan (@usrnatc ) (Nathan Corcoran)
- Alysha (@alyshaziya ) (Alysha Ismail)
