### ISSUE TITLE
Team 8 - Sprint 3 - Resources

### ISSUE THREAD

**Issue by HaroldHS** [UQdeco2800/2022-studio-3#155]
# **Description**
In this feature, tasks for resources are tasks that are related to the interaction of previous feature which is friendly worker units (#98). In this feature, team 8 will work on how to generate resources, the animation of resources, etc.

## **Examples**
- **Path finding**: worker approach the resources by using path finding algorithm instead of clicking the target resource.
- **Resources animation**: Resources will seems smaller by the time when worker collecting resources 
- **Resource genration**: Spawing resources on the map based on the weather condition
- **Update resource stats**: Updating the bases resource stats in the screen

# **Dependencies**
- Weather condition to determine the process of spawing / generating resources (#xx).

# **Milestones**
- [ ] Path finding for worker to approach resources (Oct. 1)
- [ ] Resources animation (Sept. 25)
- [ ] Resources spawn / generation (Sept. 27)
- [ ] Updating resource stats on the screen (Sept. 29)

**Completion Deadline:** Oct. 3

# **Documentation**
Wiki pages related to documentation on resources for workers

# **Members**
- Lorenzo (@lorenzopolicar) (Lorenzo Policar)
- Harold (@HaroldHS) (Harold Hotma Sibuea)
- Wishnu (@hazlazuardi) (Wishnu Hazmi Lazuardi)
- Yash (@yashvardhanbatra) (Yashvardhan Batra)
