### ISSUE TITLE
Team 1 Sprint 3 : Feature Ticket - Spells (Godpowers)

### ISSUE THREAD

**Issue by JiashengLi** [UQdeco2800/2022-studio-3#157]
# **Description**
We will start a new chapter in sprint 3 focusing on the functionality and interactions of the game. This sprint we will be making things for consistent across the game and some final details of the information box's display effect and the compatibility of the unit selection function, Improvements in overall UI in terms of consistency. 

But our main focus for this sprint will be responsible for the design and development of the climax of the in-game combat system - **Spells**.

Spell, similar to the nirvana in the Mugen game, or the 'R' skill Ultimate or even Q and E abilities in the League of Legends, usually requires a high time and resource cost to support the release, and is unlocked through additional interactions and operations.

In this game, Spell will obtain the resources/energy bar required to release the spell by _**knocking down enemies/collecting materials**_ and other positive operations. Whenever the resource/energy bar reaches a certain value, its release is unlocked, and all energy bars are cleared after release. The spell/spells will be inspired by the gods of Greek mythology. 

**Below are some of the Greek Gods and their powers** 

- **Zeus**- God of the Sky 
- **Poseidon**- God of the Sea
- **Ares**- God of War 
- **Aphrodite**- Goddess of Love
- **Hera**- Goddess of Women
- **Demeter**- Goddess of Harvest
- **Athena**- Goddess of Strategy
- **Apollo**- God of the Sun, Music and Poetry
- **Artemis**- Goddess of the Hunt
- **Hephaestus**- God of Fire
- **Hermes-** the Messenger God
- **Dionysus**- God of Wine_

Spell has unique hotkey.

The form of Spell may be a **medium-range circular AOE attack** at any location, only dealing damage or even kill enemy units, and may design special effects (such as slowing and paralysis to enemy who were hit but were on the outskirts of the damage radius range) in the future.

The area where the spell needs to be casted will be determined via a crosshair like indicator which is moved by your mouse movement and clicking. 

## SubFeature/component (optional)

We will also complete the linking workflow in Sprint3:

Remaining unit-selection to-dos:
* Compatible with the selection function between friendly units to unify the operation process.
* Redesigned the internal distribution of the Information box for better space distribution in order for all components/attributes of entity and units to be displayed.  
* Provided the avatar (picture) of each friendly unit to display in the info box as an art design.

## **Examples (optional)**
- **Spell Bar**: Certain operations will accumulate the powerbar, and releasing the spell will empty them. This should be like the powerbar in KOF 97:
 ![image](https://user-images.githubusercontent.com/88020895/190966860-ebe838d2-221a-4c2d-a9ad-6d674cd6d384.png)

- **Spell Attack Range**: ???(Still need discussion)

- **Unified Unit Selection**: Both buildings, worker units and solider units using our selection method & highlight effect, and there should be no boxboy anymore.

 - **Friendly Units Avatar**: The space on the left side of the information-box will show the images we designed for the units, presenting their appearance in a different style and perspective.
# **Dependencies**

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Finish the unit selection unify (Sep. 19)
- [ ] Design & let the unit picture shown in infobox (Sep. 24)
- [ ] Design the spell's affect, art form and animation (Sep. 24)
- [ ] Find ways to build up spell bars from other game actions and try to technically eliminate enemies (Sep. 30)
- [ ] Final implementation (Oct. 02)

**Completion Deadline:** Oct. 03

# **Extras (optional)**
- [ ] Extra components that you may implement if you get time.
- [ ] ...

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- ...

# **Members**
- Akshath(@Akshath-K ) (Akshath Katyal)
- Jackie(@jackieooikk ) (Jackie Ooi)
- Lee(@JiashengLi ) (Jiasheng Li)
- Sourav(@Sourav-RC ) (Sourav Roy Chowdhury)
- Kawhi(@jiupinbaocha )(Yi Yu)
