### ISSUE TITLE
Component of City

### ISSUE THREAD

**Issue by Fengqi0822** [UQdeco2800/2022-studio-3#159]
# **Description**
**Task:** [Component of City](#3).
**Feature:** [https://github.com/UQdeco2800/2022-studio-3/issues/152#150](#2)
The task will complete the design of library, blacksmith and city tile.
 
## **Example (optional)**
- **Part**: Depending on the task, you may want to provide some examples of how it would play out in the game. See next point for example...
- **Armour Benefits**: Players can wear different classes of armour. Armour takes damage until it breaks. Armour cannot be healed but can be replaced. If a player is wearing armour, its health is not affected when it takes damage unless the armour is broken.

# **Dependencies**
None

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Library design (Sep. 21)
- [ ] city tile design(Sep. 22)
- [ ] blacksmith design(Sep. 23)

 
**Completion Deadline:** Sep. 25

 
# **Documentation**
Not yet
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- Fengqi Yu(@Fengqi0822) (Fengqi Yu)
