### ISSUE TITLE
Implement Friendly Units Pathfinding Algorithm

### ISSUE THREAD

**Issue by lorenzopolicar** [UQdeco2800/2022-studio-3#16]
# **Description**
**Task:** Friendly Units Pathfinding Algorithm
**Feature:** #5 

This path-finding algorithm allows optimal unit movement from point A to B, considering the terrain, blocked paths, and enemy attacks. This allows the units to arrive at the allocated destination in an efficient and swift manner to avoid negative impacts on unit stats  (morale, fatigue, health). The A* pathfinding algorithm will be implemented as it is one of the best pathfinding algorithms when we have to find the shortest path between two nodes.

To implement this we need to:
- build a path each time a unit is assigned a task
- check every next step and if it is impassable (e.g. blocked by a house), recalculate and rebuild the path
- check every next step and if it is blocked by another unit - do a quick side-step around it or wait a bit for it to walk away - because units are small and mobile
- assign weighting on areas - for example, if you have a series of nodes to get to a destination that involves water which is slower and takes more steps and then crossing a bridge, the AI should opt for the more optimal path in terms of speed and accessibility
- maintain areas connectivity map, to quickly discard pathfinding between unconnected areas on the map

Resources:
How to Implement RTS Group Movement:
https://sandruski.github.io/RTS-Group-Movement/
Tutorial on A* Implementation in a game:
https://www.youtube.com/playlist?list=PLFt_AvWsXl0cq5Umv3pMC9SPnKjfp9eGW

## SubFeature/component (optional)
- Unexpected collision avoidance strategy - Upon detection of a moving unit or a new building, recalculate a new path. If there are multiple units on the move, update their paths based on the distance from the new building. The closer the path nodes are to the new building the higher the update priority.
- Enemy avoidance strategy - Upon detection of a nearby moving enemy, allow for a retreat or a reasonable distance between the enemy path and the unit path

## **Examples (optional)**
- If a unit’s straight line path is blocked by multiple buildings, the unit finds a path around them that takes the least steps.
- If there is an enemy attack nearby, the unit finds a path that maintains a distance between the enemy. If the enemy is too near and moving fast, the unit should retreat.
- If there is a body of water that separates the units from the destination, the algorithm should calculate whether the units should swim or find a nearby bridge and see which path costs less. 

# **Dependencies**
Pathfinding will rely on the map layout, and how entities/objects are stored for the map - Team-6 Sprint-1 Map Feature #3

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Implement Basic Path-finding Algorithm 
- [ ] Implement Unexpected Collision Handling Strategy
- [ ] Implement Enemy Avoidance Strategy
- [ ] Final Testing

**Completion Deadline:** Aug. 29 - Monday, Week 6 (prior to the completion of Sprint 1)

# **Documentation**
- Javadoc will be created for this unit pathfinding movement 

# **Members**
Thomas (@thomas-keevers) (Thomas Keevers)
Alex (@KungKemi) (Alexander Johnson)
Lorenzo (@lorenzopolicar) (Lorenzo Policar)
Harold (@HaroldHS) (Harold Hotma Sibuea)
Wishnu (@hazlazuardi) (Wishnu Hazmi Lazuardi)

**Comment by HJPearce** [comment]
Parts of this task will have to be refactored for shared functionality w/ #8 (basic navigation w/out enemy avoidance)
