### ISSUE TITLE
Sprint 3 Team 4 Ranged attack for trebuchet task

### ISSUE THREAD

**Issue by DLAmeng** [UQdeco2800/2022-studio-3#166]
# **Description**
**Task:** Ranged Attack for trebuchet.
**Feature:** ranged attack the enemy buildings，such as ships.
 
## **Example**
When the enemy's building is within the attack range of the trebuchet, the trebuchet will throw stones.

# **Dependencies**
- [x] Ship design (#xx)
- [x] Trebuchet Design (#xx)
 
# **Milestones**
- [x] Implement the trebuchet and ship entities (Sep. 24)
- [x] Complete the ranged attack task for trebuchet (Sep. 25)
- [x] Finish the wiki pages and unit tests (Sep. 26)
 
**Completion Deadline:** Sep. 26
 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Zhiyuan Xu (DLAmeng) (Zhiyuan Xu)
