### ISSUE TITLE
Team 6 - Map Building Graphic Design

### ISSUE THREAD

**Issue by MaxJenko** [UQdeco2800/2022-studio-3#168]
# **Description**
**Task:** Map Building Graphic Design(#3).
**Feature:** [Team 6 Sprint 3 - Map Design](#2)

In order for the game to be playable, buildings are necessary as they provide components that the player can interact with. The buildings created will go through initial drafting as drawings and once collaboration is completed with group members they will be finalised into graphic designs. Some specific designs would create a more immersive experience for the player if they were animated. The plan is to initially create static buildings, but if there is more time they will be completed during Sprint 3. Otherwise, that will be a focus for Sprint 4. Through the use of an atlas file, multiple variations of a tile can be created and the game will cycle through them, giving the impression that they are moving. Additionally, buildings will all need 4 variations so that the entrance is accessible to the player regardless of what section the building is located within the map. 
 
## **Example**
- **Map Component**: I have been assigned with creating the graphic design for the Farm, Base Gate & Cobbled Paths

# **Dependencies**
Initial drafts of the Farm, Base Gate and Cobbled Path Tile
Style of the grass tile the group implements so that my buildings appear seamless on the map
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 Draw draft versions of Farm, Base Gate and Cobbled Path Tile (Sep. 22)
- [x] Step 2 Create 4 Variations of Farm Building (Sep. 25)
- [x] Step 3 Create 4 Variations of Base Gate Building (Sep. 29)
- [x] Step 4 Create Cobbled Path Tile (Oct. 2)
 
**Completion Deadline:** Oct. 3
 
# **Documentation**
- Uploading finished products to the group discord for team recommendations

# **Member**
- Max Jenkins (@MaxJenko)
