### ISSUE TITLE
Implement Pseudorandom Number Generator (PRNG)

### ISSUE THREAD

**Issue by Corfliss** [UQdeco2800/2022-studio-3#17]
# **Description**
**Task:** Implement Pseudorandom Number Generator (PRNG) 
**Feature:** Random Event Generator (#6)

Implement an abstract class of Pseudorandom Number Generator (PRNG) `PRNG` for multiple purposes. This class can be used as a generic class to generate randomness, it can be used by other teams who are looking to use randomness in their features. Other teams could specify what features they want and we could implement this for them in this class.
 
## **Example**
* A method might exist that takes a number such as 100 and gives a random integer between 0-100.
* A method to make a worker/soldier/enemy unit stats.
* A method for time-based events.

# **Dependencies**
This ticket is not relying on any other tickets.
 
# **Milestones**
List of steps that need to be completed for this task:
- [x] Choose the person to implement the task
- [x] Implement the `PRNG` abstract class
- [x] Verifying the work as a team
 
**Completion Deadline:** Monday, Week 5 (Aug. 22)

# **Documentation**
-  [Pseudorandom Number Generator wiki](https://github.com/UQdeco2800/2022-studio-3/wiki/Pseudorandom-Number-Generator).
- `PRNG` javadocs will be explained later
 
# **Member**
@jordanlbf
