### ISSUE TITLE
team 1 sprint 3 task ticket: Perfection of Unit Selection

### ISSUE THREAD

**Issue by JiashengLi** [UQdeco2800/2022-studio-3#170]
# **Description**
**Task:** The perfection of unit selection.
**Feature:** [Feature which this tasks contributes to implementing](#2)

In sprint 3, the cross-team co-op project for unit selection and some of the details of infobox still need to be refined to achieve full development.
Cross-team co-op: We need to make sure that all friendly units under the responsibility of other teams use **the same type of selection and interaction** to avoid overloading the player.
_The friendly unit highlight feature, which has not yet been implemented in Sprint 2, also needs to be updated in parallel._

Infobox detailing: We will redesigned the size and white space distribution for the infobox to accommodate the display of the following information:
* The avatar images of all friendly units, as we designed them
* Name of the friendly unit
* Attributes of the friendly units.
*  _The attributes are displayed in format: attribute icon - attribute name - attribute value_

## **Example**
- **Worker Units**: they will using our sprint 1's unit selection logic but doing their functionality by other team's work. Once the worker is selected, their picture and name will shown on the infobox.

# **Dependencies**
- [ ] Dependency 1 (#xx)
- [ ] Dependency 2 (#xx)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Redesign the infobox & pictures (Sep. 17)
- [ ] Let the design implemented into the game (Sep. 25)
- [ ] User testing & get a design iteration (Sep. 30)
 
**Completion Deadline:** Aug. 23

 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
To be decided.
