### ISSUE TITLE
Team 8 - Polishing worker

### ISSUE THREAD

**Issue by HaroldHS** [UQdeco2800/2022-studio-3#173]
# **Description**
**Task:** [Polishing worker](#173).
**Feature:** [Team 8 - Sprint 3 - Resources](#155 )
There are some left over issues when working on worker feature for the past 2 sprints. Since, no one is working on those issues, team 8 will working on them. One of the main issues is bug, such as `worker flee` feature. For the rest tasks, most tasks are related to improve features that had been done from the last 2 sprints.

## **Example (optional)**
- **Fixing worker bug**: Fixing the bug mentioned in [Moving workers into some buildings causes them to return to base](#158).
- **Worker sprites**: Update the worker animation with the latest worker sprites instead of the old sprites.

# **Dependencies**
This task doesn't has no dependencies.
 
# **Milestones**
- [x] Fix `worker flee from approaching enemies` bug (Sept. 29)
- [x] Use the latest worker sprites (Sept. 29)
- [x] Creating more unit test for worker (Sept. 29)
 
**Completion Deadline:** Oct. 3
 
# **Documentation**
Updating each wiki pages related to the worker
 
# **Member**
- Lorenzo (@lorenzopolicar) (Lorenzo Policar)
- Harold (@HaroldHS) (Harold Hotma Sibuea)
- Wishnu (@hazlazuardi) (Wishnu Hazmi Lazuardi)
- Yash (@yashvardhanbatra) (Yashvardhan Batra)
