### ISSUE TITLE
Team 5- Sprint 3- Improved Cutscenes

### ISSUE THREAD

**Issue by yobicakes** [UQdeco2800/2022-studio-3#174]
# **Description**
**Task:** [Cutscenes](#3)
**Feature:** [New UI/Tutorial/Cutscenes](#2)

The new and improved cutscenes will present the game in the form of an interesting story narrated by "Amphitrite", the sea goddess. It will follow the conflict in question and establish why Atlantis is under attack. Users will have the option to view the story as they wish to (by selecting the "next", "previous") or "skip" ahead (considering recurring users). The main change in the "improved" cutscenes is the design, story and "previous" button. 
 
## **Example**
- **Cutscene**: User can read the story and click on "next" as per their conveinience. In the event that a user wishes to skip straight to gameplay, they may use the "skip" button. 

# **Dependencies**
The improves cutscenes follow from the previous "cutscenes" implementation and take into account all the dependencies from previous. Hence, basic sound would still be required in the background. 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Decide on cutscene Story- new (Sep. 17)
- [x] Cutscene Background design- new (Sep. 20)
- [x] Cutscene Dialogues- new (Sep. 20)
- [x] Cutscene Skip, Previous, Next buttons implementation (Sep. 25)
 
**Completion Deadline:** Sep. 28

# **Member**
- Neha (@yobicakes ) (Neha Tewari)
