### ISSUE TITLE
Team 8 - Resource spawn / generation

### ISSUE THREAD

**Issue by HaroldHS** [UQdeco2800/2022-studio-3#175]
# **Description**
**Task:** [Resource generation](#175).
**Feature:** [Team 8 - Sprint 3 - Resources](#155)

Mining camps will spawn stones around them for miner to mine. When miner had mined on of the stone of a mining camp, at a certain interval of time, a new stone will be regenerated.
 
## **Example**
- **Mining camp spawn stones**: Mining camp will spawn stones around it for miner to mine.

# **Dependencies**
This task has no dependencies.
 
# **Milestones**
- [x] Create mining camp factory (Sept. 29)
- [x] Add AI task to mining camp for generating stones (Sept. 29)
- [x] Add time functionality to spawn / generate stones at a certain time (Sept. 30)
 
**Completion Deadline:** Oct. 3
 
# **Documentation**
- Updated wiki page on how the resource generation works
 
# **Member**
- Lorenzo (@lorenzopolicar) (Lorenzo Policar)
- Harold (@HaroldHS) (Harold Hotma Sibuea)
- Wishnu (@hazlazuardi) (Wishnu Hazmi Lazuardi)
- Yash (@yashvardhanbatra) (Yashvardhan Batra)
