### ISSUE TITLE
Team 8 — Create Builder unit sprite sheet and atlas

### ISSUE THREAD

**Issue by hazlazuardi** [UQdeco2800/2022-studio-3#176]
# **Description**
**Task:** Create Builder unit sprite and atlas(#3).
**Feature:** Friendly Worker Units Continued(#98)

The sprite sheet includes three types of animation: walking, building, and highlighted. Walking animation (move) has four direction: forward-left, forward-right, back-left, back-right. Building animation (action) has two direction: forward-left and forward-right. Highlighted sprites (highlighted) are the ones that should be activated if the player selects the unit.

In the atlas, each animation starts from index 0. For each of the animation group, they have the same naming.
 
## **Example**
- **builder_forward_left_move**:  A group of sprites for Builder unit that is facing left and forward and has walking animation. 
- **builder_forward_right_action**: A group of sprites for Builder unit that is facing right and forward and has building animation. 

# **Milestones**
List of steps that need to be completed for this task.
- [x] Builder animation for walking (Sep. 28)
- [ ] Builder animation for building (Sep. 30)
- [ ] Builder animation for highlighted (Sep. 1)
 
**Completion Deadline:** Sep. 2

# **Progress**
- [x] Initial design of `Builder` created (Sep. 28).
- [x] Sprites for walking animation created for each direction (Sep. 28).
- [x] Documentation of `Builder` sprite sheet and atlas updated on wiki (Sep. 29).
 
 
# **Member**
- Wishnu (@hazlazuardi) (Wishnu Hazmi Lazuardi)
