### ISSUE TITLE
Design of building and map

### ISSUE THREAD

**Issue by Fengqi0822** [UQdeco2800/2022-studio-3#178]
# **Description**
**Task:** [Design of building and map](#3).
**Feature:** [Team-6 Sprint 3 Map design](#2)
Buildings are required for the game to be playable because they offer the player-interactable components. The buildings will initially be drafted as drawings, and once group participation is complete, they will be finalised as graphic designs. If certain designs were animated, the player would experience the game more fully. Buildings will initially be static, but if more time is available, they will be finished during Sprint 3. Otherwise, Sprint 4 will concentrate on that. An atlas file can be used to create numerous variations of a tile, and the game will cycle through them to make it appear as though they are moving.

# **Dependencies**
The draft of the design work

e.g.
- [ ] Texture needs to be created for armour laying on map.
- [ ] Texture needs to be created for player wearing armour.
- [ ] Textures need to be created for partially, and then fully, broken armour.
- [ ] Mechanism needs to be implemented for armour to be placed onto map.
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1  draw the graphic design of city tile (Sep 22)
- [ ] Step 2  design of blacksmith building (Sep 25)
- [ ] Step 3  design of library (Sep 28)
- [ ] Step 4 improves the design work and redeign a tile connect sand and city(Oct 1)
 
**Completion Deadline:** Oct 2

 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- e.g. Fengqi Yu(@Fengqi0822 )(Fengqi Yu)
