### ISSUE TITLE
Team 6 Map generation task

### ISSUE THREAD

**Issue by kaitlyn-lake** [UQdeco2800/2022-studio-3#18]
# **Description**
**Task:** [Map static & procedural generation]
**Feature:** [Team-6 Sprint-1 Map Feature](#3)

This task will be focused on implementing the internal data structure and procedural and static generation of the map. It will use appropriate data structures (e.g. arrays) to store the map and appropriate algorithms to generate the map.
 
## **Example (optional)**
- **Procedural aspects**: The island shape encompassing Atlantis will be varied through each playthrough. Additionally, resources necessary for growth, repair and victory will be distributed procedurally to prevent gameplay becoming static.
- **Static aspects**: The city itself will be a static collection of buildings and paths that will be placed somewhere on the generated island

# **Dependencies**

- [x] Tile development (#4)
- [x] Map design (#xx)
 
# **Milestones**

- [x] Internal map data structure
- [x] Rudimentary map generation algorithm
- [ ] Integration of tile entity classes with map generation functions
- [x] Unit testing
- [x] Documentation of code
 
**Completion Deadline:** Aug. 29
 
# **Documentation**

2022-studio-3 game-engine wiki - [Procedural Map Generation](https://github.com/UQdeco2800/2022-studio-3/wiki/Procedural-Map-Generation)
 
# **Member**

Ryan (rjg1) (Ryan Gibbons)
Kaitlyn Lake (kaitlyn-lake) (Kaitlyn Lake)
