### ISSUE TITLE
Health Bars

### ISSUE THREAD

**Issue by hugh5** [UQdeco2800/2022-studio-3#180]
# **Description**
**Task:** [Health Bars](./Health-Bars).
**Feature:** N/A (Task is a feature)

Health Bars will display below entities. These health bars will have segments within the bar to show amounts of health. Enemy and Friendly entities will have different coloured health bars. Health bars will hide after a period of inactivity (e.g. health hasn't change in 15 seconds). The health displayed by the health bars will be the health specified by the Combat Stats Component.

Health Bars for Buildings might also be display in the Info Box upon selection.

# **Dependencies**

- [ ] Health bar component will need to be added to newly implemented entities in this sprint (#xx)
- [ ] The Info Box display health bar depends on whether there is real estate left in the info box (#xx)
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Entity Health Bars implemented (Sep. 27)
- [ ] Wiki Documentation (Oct. 3)
 
**Completion Deadline:** Oct. 3
 
# **Documentation**
- [Wiki](../wiki/Entity-Health-Bars)
 
# **Member**
- Hugh Drummond (@hugh5)
