### ISSUE TITLE
Pathfinding Movement 

### ISSUE THREAD

**Issue by lorenzopolicar** [UQdeco2800/2022-studio-3#186]
# **Description**
**Task:** [Pathfinding Movement] 
**Feature:** [Team 8 - Sprint 3 - Resources] #155

Update the WorkerMovementTask to use a Breadth-First Search pathfinding algorithm so that workers can go to locations and avoid obstacles so that they won't get stuck. A Breadth-First Search Algorithm was used to find the optimal path for workers. The Breadth First Search Algorithm will return a list of GridPoints for the worker to traverse through to arrive at the final location. 
 
## **Example (optional)**
- When a user selects a location for the worker to go to but there is an obstacle within its straight line path, the search algorithm will calculate a path that avoids the positions that this obstacle occupies. Thus, this pathfinding allows to worker to conveniently take the fastest route and avoids any obstacles between its current position and its final position. 

# **Dependencies**
This task depends on the methods written in the MapService class, which has static methods for converting Vector2 positions to  GridPoint positions in the isometric map. It also contains a method for finding all occupied positions by entities with MapComponents as well as the Breadth-First Search Pathfinding algorithm.

e.g.
- [x] Vector2 needs to be calculated to GridPoint2 
- [x] A list of all occupied positions needs to be found to get a path
- [x] A path needs to be calculated from the worker's starting position to the user's selected destination
 
# **Milestones**
- [x] Implement the Pathfinding to the WorkerMovementTask 
- [x] Fix bugs with getAllOccupiedPositions 
- [x] Find a way to deal with cases where the BFS algorithm returns an empty list path
- [x] Test for average cases and with edge cases - no obstacle, with one obstacle, and with multiple obstacles
 
**Completion Deadline:** Oct. 3
 
# **Documentation**
- [Main description of feature](../wiki/Pathfinding-For-Workers)
 
# **Member**
- Lorenzo Policar (@lorenzopolicar ) (@lorenzopolicar)
