### ISSUE TITLE
Create Builder Units

### ISSUE THREAD

**Issue by lorenzopolicar** [UQdeco2800/2022-studio-3#187]
# **Description**
**Task:** Create Builder Units 
**Feature:** #155

Builders are a unit that is responsible for fixing and constructing buildings. We will introduce a builder unit as a medium for "spending" the resources that were collected by the workers to fix buildings that were destroyed and deteriorated by enemy units. 
 
## **Example (optional)**
- A builder will restore 10 hp points on collision with a building entity that have been dealt damage by enemy units
- A builder will use 5 of each resource to fix the building and level it up 
- A builder will return to the town hall if they have insufficient resources required to fix the building 

# **Dependencies**
- BuildingAction component to trigger the level-up event
- CombatStatsComponent to check and add the health of a building entity

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Create sprites, animation, and movement tasks for the Builder unit 
- [ ] Create a building fix component for the builder
- [ ] Create a builder factory 
- [ ] Test the Builder if it fixes buildings 
 
**Completion Deadline:** Aug. 23
# **Documentation**
- [Main description of feature](../wiki/Builder-Worker-Unit)
 
# **Member**
- Lorenzo Policar (@lorenzopolicar)
