### ISSUE TITLE
Re-design of Beach and Ocean Tiles

### ISSUE THREAD

**Issue by syl2211** [UQdeco2800/2022-studio-3#188]
# **Description**
**Task:** [Re-design of Beach and Ocean Tiles](#3).
**Feature:** [Feature which this tasks contributes to implementing](#2)

After Sprint 2, it came to the studio's attention that the map tiles seemed incomplete especially were the ocean met the sand. Additionally, the ocean tiles didn't resemble the ocean so a re-design of the tile was necessary. The re-design of the beach and ocean tiles will include all orientations to give the map a more realistic feel.  

# **Dependencies**
- [ ] Map generation 
 
# **Milestones**
- [ ] Completed re-design of the ocean tiles (Sep 28)
- [ ] Completed re-design of the beach tiles (Oct 2)
- [ ] Documentation of the new tiles (Oct 3)
 
**Completion Deadline:** Oct. 3
 
# **Documentation**
- [Game Tiles](../wiki/Feature)
.
# **Member**
- e.g. Sylvia Chen (@syl2211 ) (Sylvia Chen)
