### ISSUE TITLE
Design Loading Bar and Health Bar

### ISSUE THREAD

**Issue by syl2211** [UQdeco2800/2022-studio-3#189]
# **Description**
**Task:** [Design Loading Bar and Health Bar](#3).
**Feature:** [Feature which this tasks contributes to implementing](./154)

After Sprint 2, it was decided that a loading bar and health bar were features missing that would contribute significantly to a user's experience because it gives feedback as to how long they may have to wait for the game to load and also how much health their troops or building has left. A design for this is needed to then be implemented into the games. 

# **Milestones**
- [ ] Complete design for loading bar (Sep 25)
- [ ] Complete design for health bar (Sep 28)
- [ ] Documentation for new features onto wiki (Oct 2)
 
**Completion Deadline:** Oct. 3 
 
# **Documentation**
- [Health Bar](../wiki/Entity-Health-Bars)
- [Loading Bar](../wiki/Loading-Screen)
 
# **Member**
- Wenfeng Wang (@WW7796332)
