### ISSUE TITLE
Team-2 Sprint-1 Buildings/Structures Feature

### ISSUE THREAD

**Issue by hugh5** [UQdeco2800/2022-studio-3#19]
# **Description**
Feature: Structure/Buildings. 
This feature relates to all buildings/structures created in the game which includes their gameplay functionality, attributes and designs. Base building is a core aspect of RTS gameplay and gives the player a way to spend resources and advance in the game. Enjoyment of the game stems from the creativity given to players in how they choose to build the vast selection structures.

## SubFeature/component (optional)
Building types: troop barracks, fence structures, builders/crafting, storage facilities (economic buildings), fortification/defensive buildings, research buildings.

Building placement: top-down grid layout (depends on camera view and map). Buildings can’t overlap each other or be placed over other objects.

Building attributes: all buildings will have a set amount of health. Buildings will cost a certain amount of resources to construct and will take a set amount of time. Placement size (how many grid squares does this building take up).

## Dependencies
Depends a bit on the map - obstacles and for placements (is the area for the placement free and taken up already) and grid coordinate system. Also need the dimensions of the map for designing building art. How big should the pixel art be for buildings and structures?

Barracks building will coordinate with thee friendly troop team and their implementation of friendly entities. (For producing friendly troop entities).

Buildings health may coordinate with the combat system to take damage

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Goal 1 (Aug. 20) (Monday, Week 4) - Outside game - building ideas and sketch designs. Pseudocode of object structure. Building interface class in java
- [ ] Goal 2 (Aug. 23) (Wednesday, Week 4) - A dummy building/structure can be crafted with resources and placed on the map and can be moved after it is placed. Design of more buildings has been completed and ready to implement.
- [ ] Goal 3 (Aug. 26) (Monday, Week 5) - Implement in game - At least 1 building and 1 structure is implemented with its features. E.g. The player can use features such as training troops in the barracks. Buildings can be placed at a point on the map.
- [ ] Goal 4 (Aug. 28) (Wednesday, Week 5) - Have at least 5 mostly working buildings/structures in game for the player to build and interact with.  Buildings that get damaged by attacks are repairable

**Completion Deadline:** Aug. 29 – Monday week 6 (Sprint 1 due date)

# **Extras (optional)**
- [ ] Building type: Housing buildings for population control.
- [ ] Building type: Defensive buildings

# **Documentation**
As we progress we will add to the wiki each building/structure that has been added to the game. This includes but not limited to – its attributes (health, required resources, build time, placement size) and usage/player interaction.

# **Members**
- Hugh Drummond (@hugh5)
- Sylvia Chen (@syl2211)
- Wenfeng Wang(@ww7796332)
- Angus Buchanan (@Spooey)
- Wenjing Shan(@nicococole)
