### ISSUE TITLE
Re-design Weather Effects - Rain and Snow 

### ISSUE THREAD

**Issue by syl2211** [UQdeco2800/2022-studio-3#192]
# **Description**
**Task:** [Re-design Weather Effects](#3).
**Feature:** [Advanced Weather Feature](./154)

After Sprint 2, it was decided there would be advanced weather effects which included a redesign of the weather effects to be more realistic, such as raindrops for rainy season and snowflakes for snowy season. These designs will then be implemented into the game. 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Complete re-design of rainy weather effect (Sep. 28)
- [x] Complete re-design of snowy weather effect (Sep. 30)
- [x] Documentation of new features on wiki (Oct. 3)
 
**Completion Deadline:** Oct. 4

# **Documentation**
- [Main description of feature](../wiki/Feature)
 
# **Member**
- Sylvia Chen (@syl2211)
- Wengjing Shan (@nicococole)
