### ISSUE TITLE
Re-design weather animation

### ISSUE THREAD

**Issue by nicococole** [UQdeco2800/2022-studio-3#193]
# **Description**
**Task: Re-design weather animation.
**Feature: [information bars and advanced weather and game tile design](https://github.com/UQdeco2800/2022-studio-3/issues/154)
The studio noted that some weather had not been designed in previous Sprint, and that thunder and rainy days had not been fully designed, so it had to be redesigned

# **Dependencies**

- [ ]  Map generation

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Re-design rain animation (Sept 29)
- [ ] Re-design snow animation (Oct 1)
- [ ] Re-deisgn thunder animation (Oct 2)
 
**Completion Deadline: Oct 3
 
# **Documentation**
- [Weather Design](https://github.com/UQdeco2800/2022-studio-3/wiki/Weather-Design)
 
# **Member**
- Wenjing Shan (@nicococole ) (wenjing)
