### ISSUE TITLE
Add rain animation to weatherIcon

### ISSUE THREAD

**Issue by Spooey** [UQdeco2800/2022-studio-3#200]
# **Description**
**Task:** [Adding rain animations to weather](#3).
**Feature:** [Team 2 sprint 3 advanced weather](#154)
The current in-game weather changes the screen brightness but has no other animations. Rain animations will be added to give more visuals and juice to the game. This animation will be used for the rain and storm weather
 
## **Example (optional)**
![image](https://user-images.githubusercontent.com/67825245/193721465-9beebbb6-c887-498a-b9b7-aa1691433bf2.png)
Minecraft rain is the style we are following.
e.g.
- [ ] Texture needs to be created for rain animations
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1 (Sep. 26): add basic rain animations to game
- [ ] Step 2 (Oct 1) Add final animation design
 
**Completion Deadline:** Oct 3.

# **Documentation**
- https://github.com/UQdeco2800/2022-studio-3/wiki/Random-Weather-Animation-Art-Design
- https://github.com/UQdeco2800/2022-studio-3/wiki/Random-Weather-Events-Design
- 
 
# **Member**
- Angus Buchanan (@Spooey)
