### ISSUE TITLE
Sprint 3- Team 5- User Testing Feedback

### ISSUE THREAD

**Issue by yobicakes** [UQdeco2800/2022-studio-3#201]
# **Description**
**Task:** [Implementing User Testing- Main Game Screen](#3)
**Feature:** [Main Menu Functionality](#2)

Implementing feedback received in sprint 1 regarding the Main Menu screen. As per User Testing, we were advised to create "hovers" for the buttons (to help the user understand that they were hovering), this feedback is also in line with Nielsen's Usability Heuristic 1 (Visibility of System Status), hence, it was important to ensure that this feedback was implemented. Moreover, we were also advised to change design and button styling aspects in the main menu screen entriely. 
 
## **Example **

- **User Interaction**: The colour of the "start" and "exit" button changes on hover and the size increases slightly. 

# **Dependencies**
There are no dependencies in this task because it follows as feedback from Sprint 3. 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Design a new main menu with the same background image but a more relevant font style (Oct. 1)
- [x] Design new button designs (Oct. 1)
- [x] Design new hover button designs (Oct. 1)
- [x] Implement hovers in game (Oct. 2)
 
**Completion Deadline:** Oct. 3

# **Documentation**
- [Main Description of feature](https://github.com/UQdeco2800/2022-studio-3/issues/50)

 
# **Member**
- Neha (@yobicakes ) (Neha Tewari)
