### ISSUE TITLE
Team 6 Mini map task

### ISSUE THREAD

**Issue by Fengqi0822** [UQdeco2800/2022-studio-3#21]
# **Description**
The Mini Map is a condensed version of the full map which will allow the player to assess the state of the game at a glance. It will be located in a standard RTS position at the bottom right of the screen. It will display key game elements, such as terrain, friendly units, enemy units, resources and buildings.

# **Dependencies**

- [ ] Friendly worker units being implemented
- [ ] Enemy units being implemented
- [ ] Buildings being implemented
- [ ] An array holding every entity at its current position within the game
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Draw a static box at the corner of the screen, that scales with Camera zoom
- [x] Draw the base map of terrain, without any entities or buildings
- [ ] Draw the entire game map, with all entities included
 
**Completion Deadline:** Aug. 29
 
# **Documentation**
2022-studio-3 game engine wiki - [Minimap Component](https://github.com/UQdeco2800/2022-studio-3/wiki/MinimapComponent)
# **Member**
Fengqi Yu (Fengqi0822) Fengqi Yu
Ryan (rjg1) Ryan Gibbons

**Comment by rjg1** [comment]
Updated details and wording of ticket
