### ISSUE TITLE
Team 7 - Sprint 4 - Refine and Improve Map Flooding and Enemy Movement

### ISSUE THREAD

**Issue by quocdat402** [UQdeco2800/2022-studio-3#216]
# **Description**
For Sprint 4, our team will focus on refining the map flooding feature, aswell as improve the movement of enemy units.

The improvement for flooding feature are as follow:
* The resources will be disposed when that area is flooded.
* Flash the next tile to be flooded few seconds before it got flooded.
* Add a visual timer on the screen.
* Make unit can no longer walk on the flooded areas of the map.
* Make floodind only happens from far left or right of the map instead of uniformly around the map.

The improvement for the movement of enemy units are as follow:
* Improve the pathfinding and the line of sight of the enemies.

A feature will be added to enemy units to give them a line of sight. Within this line of sight, enemies will be able to recognise friendly units and lock onto them. When an enemy unit is not locked onto a target, it will undeterministically roam the map. Basic pathfinding will be implemented to help enemy units avoid nearby objects.

## **Examples**
* Friendlies cannot walk on the water area if it is flooded. As well as enemy types who only can walk on land.
* Dispose area of movement after the flooding.
* The visual timer will be represented with a bar with multiple stages, indicating the flooding timer.

# **Dependencies**
* Map feature
* Enemy movements

# **Milestones**
- [x] Implement the timer using flooding bar (Oct 13)
- [x] Resource disposal when flooded (Oct 13)
- [x] Flash next tiles few seconds before being flooded (Oct 13)
- [ ] Make friendly units unable to go to the flooded area (Oct 13)
- [x] Improve pathfinding for enemeis (Oct 13)

**Completion Deadline:** Oct. 17

# **Documentation**
* [Map Flooding Design](https://github.com/UQdeco2800/2022-studio-3/wiki/Map-Flooding-Design)

# **Members**
* Junyao Li (@lijunyao1) (Junyao Li)
* Fauzan Hanandito Chaidir (@Corfliss)
* Quoc Dat Mai (@quocdat402) (Dat Mai)
* Haozhe Ding (@RichardD02) (Haozhe Ding)
* Jordan Brewis Foulger (@jordanlbf)
