### ISSUE TITLE
Team 5 - Sprint 4 - Tutorial (Interactive)

### ISSUE THREAD

**Issue by alyshaziya** [UQdeco2800/2022-studio-3#218]
# **Description**
**Task:** [Team 5 - Sprint 4 - Tutorial (Interactive)](#3).
**Feature:** [Feature](https://github.com/UQdeco2800/2022-studio-3/issues/229)

Implementing an interactive optional tutorial for the game to enhance playability. The feature will prompt the user to complete specific tasks (eg select troops, level up base, collect resources, train troops) to teach players the key gameplay mechanics. Last sprint, a generic tutorial was made which is standalone from the main game (this was done to ensure we dont break anything in the main game, and to be able to build on this functionality). For this sprint, we will aim to move from a generic tutorial to 
an interactive one which simulates a lower difficulty of the game, and upon completion the player will have the required knowledge to play the game at a basic level. 

## **Example (optional)**
- **Spell**: For example, players are able to use spells to defeat enemies. The tutorial should spawn low level enemies and prompt the player to use a spell to defeat them. This ensures players are familiar with the spell system. 
- **Troops**: Players can spawn many different kinds of troops (worker and soldiers) and ensuring the player is able to use both appropriately is one of the basic knowledge required to play the main game. 

# **Dependencies**
This ticket relies on having a valid combat system for one of its sub goals - for now we have spell casting, troop spawning but a clear combat system is needed. 

# **Milestones**
List of steps that need to be completed for this task.
- [x] Spawn enemies at certain times (Oct 13)
- [ ] Add event listeners for buttons (Oct 13)
- [x] Add component specific dialogue (Oct 13)
- [x] Continuously document chronological order of events (Oct 17)
 
**Completion Deadline:** Oct 17

# **Documentation**
- [Tutorial description & code guide, UML](https://github.com/UQdeco2800/2022-studio-3/wiki/Interactive-Tutorial)

 
# **Member**
- Alysha Ismail (@alyshaziya ) (Alysha Ismail)
