### ISSUE TITLE
Team 8 Sprint 4 - Soldier Units

### ISSUE THREAD

**Issue by lorenzopolicar** [UQdeco2800/2022-studio-3#220]
# **Description**
For sprint 4, team 8's main focus is improving and making the combat system/units functional to enhance the user's game experience. Movement and pathfinding will be integrated with the friendly soldier units. Selections and attacking are functionalities that will be made visual and interactive so that there is visual feedback for the user. 

## SubFeature/component

- **Implement highlighted sprites to visualise selection of friendly units**: At the moment, there is no visual feedback for the user when they select units. We will be making units "highlighted" using the highlighted sprites for each worker when they are selected.
- **Adding movement, pathfinding and attacking strategy for soldiers**: Soldiers are not moving so we will be giving them a movement task and plan a way for soldier units to attack the enemy and win the game.
- **Spell Economics (Cool down and economics)**: There should be cool down applied to the spell so user's won't be able to spam the spell and win the game easily. The time of cooldown will be determined through user testing. Resources should also be expended when activating the spell. Adding this layer of difficulty for the user will keep the game interesting.
- **Archer Animations** - as Archers are a subunit of the combat units they should act differently during combat and shoot arrows when placed in the right location. 
- **Adding more unit and integration tests for the friendly units** - tests will cover the functionalities of the friendly units more. Movement and attacking will be tested.
- **Update Documentation** - Wikis for the friendly units will be updated with their respective UML and sequence diagrams
- **Music and Sound FX** - Collab with team 2 to improve auditory experience for the user.

# **Dependencies**
- Components owned by the friendly units (i.e. TroopComponent)
- MapService should be fixed so that Pathfinding is functional for soldier units
- Components of the Spell Activation and the Base's ResourceStatsComponent

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Implement highlighted sprites to visualise selection of friendly units 
- [ ] Adding movement for soldiers 
- [ ] User Testing
- [ ] Attacking strategy
- [ ] Spell economics (cool down & resources) 
- [ ] Documentation (UML & Sequence diagram) 
- [ ] Archer Animation

**Completion Deadline:** Oct. 17

# **Members**
- Lorenzo (@lorenzopolicar) (Lorenzo Policar)
- Harold (@HaroldHS) (Harold Hotma Sibuea)
- Wishnu (@hazlazuardi) (Wishnu Hazmi Lazuardi)
- Yash (@yashvardhanbatra) (Yashvardhan Batra)

-
