### ISSUE TITLE
Team 8 - Sprint 4 - Spell economics

### ISSUE THREAD

**Issue by HaroldHS** [UQdeco2800/2022-studio-3#221]
# **Description**
**Task:** [Team 8 - Sprint 4 - Spell economics](#221).
**Feature:** [Team 8 Sprint 4 - Soldier Units](#220)

Spell economics focus on how to use resources to release spell in the game. In addition, this could limit the user to spam the spell in the game in order to make the game not being easy to win. The resources to be used for the spell are stones, metals, and wood. When user have no resources, user can't cast the spell.
 
## **Example**
- **Number of resources to cast the spell**: Spell requires some minimum amount of metals, stones, and woods.
- **Cool down**: Minimize the number of spell to be casted (to reduce spam from the user)

# **Dependencies**
This task has no dependencies
 
# **Milestones**
- [x] Integrate spell with BaseComponent that store the resources (Oct. 9)
- [x] Update the resource stats display everytime the spell casted (Oct. 9)
- [x] Test the edge case of the spell (Oct. 10)
 
**Completion Deadline:** Oct. 10
 
# **Documentation**
- [Wiki page describing the spell]()
 
# **Member**
- Lorenzo (@lorenzopolicar) (Lorenzo Policar)
- Harold (@HaroldHS) (Harold Hotma Sibuea)
- Wishnu (@hazlazuardi) (Wishnu Hazmi Lazuardi)
- Yash (@yashvardhanbatra) (Yashvardhan Batra)
