### ISSUE TITLE
Polishing Health Bars

### ISSUE THREAD

**Issue by hugh5** [UQdeco2800/2022-studio-3#224]
# **Description**
**Task:** [Polishing Health Bars](./224).
**Feature:** [Information Bars](./154)

A lot of entities are missing health bars and some are the wrong colour. As the pull requests were made in the last few days of sprint 3, there wasn't enough time to add them to every entity. 
Allow the health bars to show when the entity is selected using `SelectableComponent`. 
Show health bar in the UI box for friendly buildings
Checking code smells for health bar code.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Add them to all entities that should have health bars
- [x] Make sure they are the correct type (friendly/enemy)
- [x] Make health bars visible upon selection of the entity
- [x] Show health bar in the UI box for friendly buildings
- [x] Fix code smells
 
**Completion Deadline:** Oct. 18
 
# **Member**
- Hugh Drummond (@hugh5 )
