### ISSUE TITLE
Team 6 sprint 4: building shop interface + polishing

### ISSUE THREAD

**Issue by kaitlyn-lake** [UQdeco2800/2022-studio-3#225]
# **Description**
The goal of this sprint is to implement building functionality and upgrade and polish other game features including MapService, city design features and fixing building selection. Create a heads-up interface for building options, and add the functionality to upgrade buildings, spawn units and spend resources. At Blacksmith walls can be upgraded, at the Library, units can be upgraded and at Barracks units can be spawned. The plan of the user test is to test all the design stuff such as the construction of the map, the colour combination of the building and so on.

## SubFeature/component (optional)
Adding building functionality
Building stats
Selection interface
Options: Upgrade, Buy
City features to make it look more alive
Fixing building selection hitboxes
Upgrade MapService to be able to know the correct position and size of an entity
Add more component of city on the city area
Polish the tile image assets of the map (sand, city and sea tile)

## **Examples (optional)**
- **Building selection**: a player will be to select a building by only clicking on that building. A building will no longer be selected accidentally due to missized hitboxes
- **Building upgrade**: once a player selects a building a heads up display will appear and they will have the option of upgrading, buying and building stats
# **Dependencies**

N/A

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Fix MapService bug resulting from scaling (October. 10)
- [x] First PR (October. 10)
- [x] Improve the sand tile and create the village house(October. 10)
- [x] Implement interface for building functionality (October. 12)
- [x] Create the water feature and animation assets (October. 12)
- [x] Create the street lamp post assets (October 12)
- [x] Improve the selection hitbox of each building (October 13)
- [x] Add building upgrade functionality (October. 13)
- [x] Second PR (October. 13)
- [x] Implement animated water feature (October. 14)
- [x] Create city trees, bushes and flowers (October 14)
- [x] Implement street lamp posts, city trees, bushes and flowers (October 14)
- [x] Unit testing and documentation (October. 15)
- [x] Final PR (October. 16)

**Completion Deadline:** October. 17

# **Extras (optional)**
- [ ] Different designs for buildings and walls based on their stats/levels
# **Documentation**
Wiki entries pertaining to the interface and algorithm design of the sprint
Javadocs
# **Members**
- Ryan Gibbons (sssss#2970)[ (rjg1](https://github.com/rjg1))
- Max Jenkins (@Jenko)[ (MaxJenko](https://github.com/MaxJenko))
- Kaitlyn Lake (@kaitlyn-lake) (Kaitlyn Lake)
- Fengqi Yu (@Fengqi0822) (Fengqi Yu)
