### ISSUE TITLE
Team 5 - Sprint 4 - Tutorial/ContextBox/End Game screen/Fred/Pause

### ISSUE THREAD

**Issue by alyshaziya** [UQdeco2800/2022-studio-3#229]
# **Description**
For sprint 4, we will focus on polishing our features to be fully functional so the game can be delivered. These features include the tutorial, which we plan to make interactive as well as animating Fred, an end game screen denoting the end of the game, context menu UI which shows info building statistics and building actions, as well as additions to the pause menu and cutscenes. 

## SubFeature/component (optional)
Cutscenes
- Cut scenes button redesigns (from user testing)

Tutorial
- Add interactivity to tutorial
- Animate Fred 

End game screen
- Implement game over screen 

Context menu 
- Implement context menu UI

Pause menu 
- Functionality

## **Examples (optional)**
- **Tutorial**: An optional tutorial be completed before gameplay to ensure user is familiar with gameplay mechanics. The tutorial is interactive and should make the player complete beginner tasks in game (ideally from each interactable feature being worked on)
- **End game**: Game over screen that should display once the game has ended 
- **Context Box**: Context menu UI for building showing current building statistics and actions. 

# **Dependencies**
- Functionality for context menu (#149).

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Cutscenes (Oct 16)
- [ ] Tutorial (Oct 16)
- [ ] End game screen (Oct 16)
- [ ] Context Menu (Oct 16)
- [ ] Pause Menu (Oct 16)

**Completion Deadline:** Oct 17

# **Extras (optional)**
- [ ] Feedback from user testing

# **Documentation**
- [Tutorial](https://github.com/UQdeco2800/2022-studio-3/wiki/Interactive-Tutorial)

# **Members**
- Nathan (@usrnatc ) (Nathan Corcoran)
- Alysha (@alyshaziya ) (Alysha Ismail)
- Tyrion (@Suuoooooooo  ) (Tiansong Zhang)
- Neha (@yobicakes ) (Neha Tewari)
- Pratham (@prathammanocha) (Pratham Manocha)
