### ISSUE TITLE
Implemented a Basic Miner Unit Class

### ISSUE THREAD

**Issue by HaroldHS** [UQdeco2800/2022-studio-3#23]
# **Description**
**Task:** Create a Basic Miner Unit Class
**Feature:** #5 

We will create a `Basic Miner` class that implements abstract `Worker` class. A `Basic Miner` class should have the following property:

1. Mining duration - Each mining process has duration based on the component to be mined (different component has different mining duration time).
 
## **Example**
- **Mining duration**: Mining wood may take less time than mining gold 

# **Dependencies**
- [ ] Implement Abstract Worker Unit Class (#13)
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Write `Basic Miner` Unit Class (TBA)
- [ ] Create tests for `Basic Miner` Unit Class (TBA)
 
**Completion Deadline:** TBA
 
# **Documentation**
* Wiki page detailing how the `Basic Miner` class will be implemented
 
# **Member**
To be decided
