### ISSUE TITLE
Team 5 - Sprint 4 - Context Box UI

### ISSUE THREAD

**Issue by usrnatc** [UQdeco2800/2022-studio-3#230]
# **Description**
**Task:** Team 5 - Sprint 4 - Context Box UI.
**Feature:** [Team 5 - Sprint 4](https://github.com/UQdeco2800/2022-studio-3/issues/229)

Implementing a UI design for the in-game context menu, used to display selected building statistics such as; building defense; . This task will allow for simple display of the required information and intuitive actions against the selected building. The design will follow an ancient Greek theme in accordance to the present game style.

# **Dependencies**
**Team 4 Sprint 3:** [Team 4 - Sprint 3 Buildings](#149)
This ticket relies on having persistent and accessible building data. Access to this data was made possible by Team 4 in Sprint 3 in their Buildings commits.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Display context box when building selected (Oct 13)
- [x] Scale appropriately based on screen size (Oct 13)
- [ ] Bind actions to buttons for buildings (Oct 13)
- [ ] Add necessary documentation; user testing, API, ... (Oct 17)
 
**Completion Deadline:** Oct 17

# **Documentation**
[Context Box Wiki](https://github.com/UQdeco2800/2022-studio-3/wiki/Building-Context-Box-UI)

 
# **Member**
- Nathan Corcoran (@usrnatc) (Nathan Corcoran)
