### ISSUE TITLE
Team 1 Sprint 4 - Personal Task Ticket (Yi Yu)

### ISSUE THREAD

**Issue by jiupinbaocha** [UQdeco2800/2022-studio-3#231]
# **Description**
**Task:** spell system, sound effect designing, button design.(#3).
**Feature:** (#2)

After sprint3 our team has finished one of the spells(zeus) and realized the release of the spell. So after that, I hold the view that it looks like a little monotony, I decided to design an another spell and also the two spells can get changes by a button in order that we can choose one we like. By the way, the different spells can give different hurt to different enemies. 

Also the buttons need to be polished, not only make it more beautiful, but also design more(like mute_button)

Then the sound effect isn't good enough, we need to do some sound. For example, if we release the spell, we want some sound effect to show the powerful of the spell. 

It should be noted that this task only involves the assistance of the UI part. The specific scope is as follows:

-  spell design. 
- button design
- sound effect design
- ....

## **Example (optional)**
- **UI Support** :Design a common UI material to support flexible calls when developing buttons in other modules.

- **Sound support**: Design some sound effect which can get use by the spell release and so on.

# **Dependencies**
The tasks depends on all functions in the game.

# **Milestones**
List of steps that need to be completed for this task.
- [ ] button design (Oct. 10)
- [ ] sound design (Oct. 15)
- [ ] spell design (Oct. 18)
 
**Completion Deadline:** Oct. 18

# **Member**
- Yi Yu(@jiupinbaocha )
