### ISSUE TITLE
Building Selection Hitboxes

### ISSUE THREAD

**Issue by rjg1** [UQdeco2800/2022-studio-3#232]
# **Description**
**Task:** [Building Selection Hitboxes](#3).
**Feature:** [Team 6 Sprint 4](https://github.com/UQdeco2800/2022-studio-3/issues/225)

Currently, Buildings are selected based off their texture hitbox in game, which is a square. This means that in congested areas of the game - notably the city - it is possibly, and even likely to click on several buildings at once with a single click, as they have overlapping texture hitboxes. This issue intends to fix this by adding a defined click hitbox to each building entity that is distinct from its texture.

This is essential to core functionality of the game, as it is very difficult to select a single instance of a building currently, which prevents adding features such as shops (i.e. barracks buying units).
 
## **Example (optional)**
- A user loads into game. They click a city wall and will only select a single wall. This can be extrapolated to any building.

# **Dependencies**
N/A

# **Milestones**
List of steps that need to be completed for this task.
- [x] Create component that functions as a hitbox for entities (Oct 14)
- [x] Change existing building selection component to use this hitbox (Oct 15)
- [x] Modify all building entities to have this functionality (Oct 16)
- [x] Create unit tests (Oct 16)
 
**Completion Deadline:** Oct 16
 
# **Documentation**
- Javadocs within code
- Wiki articles documenting process and changes
 
# **Member**
- Ryan Gibbons (sssss#2970)[ (rjg1](https://github.com/rjg1))
