### ISSUE TITLE
Building shop

### ISSUE THREAD

**Issue by kaitlyn-lake** [UQdeco2800/2022-studio-3#233]
# **Description**
**Task:** [Building shop](#3).
**Feature:** [Team 6 sprint 4: building shop interface + polishing](#225)

When a player selects certain buildings, they will have a shop interface where they will be able to trade resources for things that help them progress the game. What they can trade resources for depends what building has been selected.
 
## **Example (optional)**
- **Library**: when a player selects the library they will be able to upgrade units
- **Blacksmith**: when a player selects a barracks they will be able to upgrade walls
- **Barracks**: when a player selects a barracks they will be able to spawn units

# **Dependencies**

- [x] A shop interface needs to be designed
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Design shop interface
- [x] Add shop interface into the game
- [x] Implement trading for each building
- [x] Unit test
 
**Completion Deadline:** Oct. 17
 
# **Documentation**

To be added.
 
# **Member**
- Ryan Gibbons (sssss#2970)[ (rjg1](https://github.com/rjg1))
- Kaitlyn Lake (@kaitlyn-lake) (Kaitlyn Lake)
