### ISSUE TITLE
Fix MapService bug

### ISSUE THREAD

**Issue by kaitlyn-lake** [UQdeco2800/2022-studio-3#234]
# **Description**
**Task:** [Fix MapService bug](#3).
**Feature:** [Team 6 sprint 4: building shop interface + polishing](#225)

The scale used to calculate the number of tiles an entity occupies is inaccurate given the actual texture, resulting in pathfinding not working properly and the mini map entities being rendered incorrectly. This will be fixed by extending TextureScalar to correctly calculte the scale of the texture, which will be used to calculate entity positions and sizes in MapService and allow units to pathfind correctly.
 
## **Example (optional)**
- **Mini map**: Entities with a MapComponent will no longer display as elongated rectangles on the mini map...

# **Dependencies**

N/A

# **Milestones**
List of steps that need to be completed for this task.
- [x] TextureScalar correctly calculates the length and width of a texture, as well as a starting coordinate
- [x] TextureScalar is added to every entity with a texture in the game
- [x] MapService switch to TextureScalar scale
- [x] Unit testing
 
**Completion Deadline:** Oct. 17
 
# **Documentation**

To be added.
 
# **Member**
- Ryan Gibbons (sssss#2970)[ (rjg1](https://github.com/rjg1))
- Kaitlyn Lake (@kaitlyn-lake) (Kaitlyn Lake)
