### ISSUE TITLE
Team 1 Sprint 4 Task ticket: Infobox final progress

### ISSUE THREAD

**Issue by JiashengLi** [UQdeco2800/2022-studio-3#235]
# **Description**
**Task:** Infobox final progress
**Feature:** 

We will optimize the internal layout of the `InfoboxDisplay` class again, including the design of the blank part, the display form of the avatar, and the icon of the unit data as an auxiliary display.
 
## **Example (optional)**
- **avatar display**: only one picture shown even if user selected more than 1 unit.
- **icon display**: the data will shown like "icon - status name - status value".

# **Dependencies**

- [ ] Dependency 1 (#xx)
- [ ] Dependency 2 (#xx)
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Redesign the icons (Oct. 12)
- [ ] Let the avatar shown once in mutiple selection (Oct. 15)
- [ ] let the icon shown onto the infobox (Oct. 16)

**Completion Deadline:** Oct.17

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Lee (@JiashengLi) (Jiasheng Li)
