### ISSUE TITLE
Team 7 - Sprint 4 - Improve Enemy Movement

### ISSUE THREAD

**Issue by jordanlbf** [UQdeco2800/2022-studio-3#238]
# **Description**
**Task:** [Team 7 - Sprint 4 - Improve Enemy Movement](#3).
**Feature:** [Team 7 - Sprint 4 - Refine and Improve Map Flooding and Enemy Movement](#216)

The movement of enemy units will have the following features:
- In general, enemy units will roam the map. They will be confined to a localised area to avoid clustering.
- Enemy units will have a line of sight where they can lock onto friendly units to attack.
 
# **Milestones**
- [x] Confine enemy units to a local area. (Oct. 12)
- [ ] Give enemy units a line of sight (Oct. 14)
- [ ] Lock enemies onto friendly units that come into their line of sight (Oct. 16)
- [ ] Resolve collisions with other units (Oct. 17)
 
**Completion Deadline:** Oct. 17
 
# **Documentation**
- [Enemy Movement](https://github.com/UQdeco2800/2022-studio-3/wiki/Enemy-Movement)
 
# **Member**
- Jordan Brewis Foulger (@jordanlbf)
