### ISSUE TITLE
Team 4 - Ticket - Create Initial Enemy Unit Entites and Components

### ISSUE THREAD

**Issue by Abishtu** [UQdeco2800/2022-studio-3#24]
# **Description**
**Task:** Create Initial two enemy unit entities and related **non-AI** components.
**Feature:** #12
Basic enemy entities and relevant **non-AI** components, this involves
* Creating factory methods ghouls and demons
* Updating combat stats component to match requirements of the combatant units.
* Might involve work with attacking, but that's most likely gonna involve AI
**Note: This does not cover creation of animation and sprite files or AI behaviour**
 
## **Example (optional)**
- **Config files**: Attack strength, defence ability, remaining health, level and how that will change other stats.

# **Dependencies**

- [x] Sprites and animations need to be made.
- [x] Common stats between friendly and enemy units need to be decided upon.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Write creation method for ghouls and demons (Aug. 17)
- [x] Update combat stats component (Aug. 19)

# **Optional**
- [x] Combat
 
**Completion Deadline:** Aug. 23

# **Documentation**
- Java doc for how unit creation works
 
# **Member**
- Harikesha Suresh (@Abishtu)
