### ISSUE TITLE
Team 5- Sprint 4- User Testing Feedback Implementation

### ISSUE THREAD

**Issue by yobicakes** [UQdeco2800/2022-studio-3#240]
# **Description**
**Task:** [User Testing Implementation](#3).
**Feature:** [Team 5- Sprint 4](https://github.com/UQdeco2800/2022-studio-3/issues/229)

The feedback collected from User Testing in sprint 3 will be implemented to ensure our game is usable. We aim to cover any quick fixes and/or full on functionality. Following this, functionality will be verified via the users. Towards, the end of the sprint, new functionality will be tested.
 

# **Dependencies**
As this is user testing implementation, there are no dependencies that follow on from the initial iteration. 

# **Milestones**
List of steps that need to be completed for this task.
- [x] Fix Buttons (Oct. 17)
- [x] Position Fred (Oct. 17)
- [x] Consistent art style (Oct. 17)
- [x] Animations in main game screen (Oct. 17)
- [x] Exapnding tutorial to all game play aspects (Oct. 17)
- [x] Animations in end game screen (Oct. 17)
 
**Completion Deadline:** 19 Oct.

# **Documentation**
- User Testing from previous sprint ([../wiki/Cutscenes, End Game Screen, Tutorial User Testing](https://github.com/UQdeco2800/2022-studio-3/wiki/Cutscenes,-End-Game-Screen,-Tutorial-User-Testing))

 
# **Member**
Neha (@yobicakes ) Neha Tewari
