### ISSUE TITLE
Implement Worker Task System

### ISSUE THREAD

**Issue by KungKemi** [UQdeco2800/2022-studio-3#25]
# **Description**
**Task:** Worker Task System
**Feature:** #5 

We will implement a task system for `Worker` units. The task system will introduce the concept of a `Task` which is a type of action that a worker unit will attempt to carry out in the game.

There will be two main types of tasks: **movement** and **interaction**.

These can be defined as follows:

1. **Movement**: an action in which a worker unit will move from their current position $(x_{0}, y_{0})$ to a new position $(x_{1}, y_{1})$ on the game map. This action will only take place if $(x_{1}, y_{1})$ is currently unoccupied; e.g., a worker unit will not move to the same position as the collision box of another entity/object.

2. **Interaction**: an action in which a worker unit interacts with an object on the map; e.g., a structure or resource node. This action will only take place if the object is considered to be **interactable** by the unit.

The interaction task can be further divided into the following:

1. **Collecting Resources**: a worker unit collects resources from a resource node. This action will only occur if:
i. The worker unit can interact with the node
ii. The worker unit has space in their inventory

3. **Delivering Resources**: resources in the worker unit's inventory are added to the total resources managed by the player.

4. **Building/Repairing Structures**: a worker unit builds or repairs a structure. This action will only occur if:
i. The worker unit can interact with the structure
ii. The structure is "damaged"
iii. The worker unit has the appropriate resources in their inventory

A task should **end** when at least one of the following conditions are met:
- The player instructs the worker unit to start on a new task
- The worker unit completes the task

## **Examples**
Consider a `Miner` unit which has been instructed to collect stone from a resource node. 

The sequence in which tasks can be executed to perform this transaction is as follows:
1. The unit performs a `Movement` task to reach the node.
2. After arriving at the node, the unit performs an `Interaction` task to collect resources.
3. After the unit's inventory is full, the unit performs a `Movement` task to return to the home base.
4. After arriving at the home base, the unit performs an `Interaction` task to deliver resources to the player.

# **Dependencies**
- [ ] The `Movement` task depends on the pathfinding AI of the worker unit
- [ ] The `Interaction` task depends on the definition of an interactable object
 
# **Milestones**
- [ ] Implement abstract `Task` class
- [ ] Write tests for children of `Task` class
- [ ] Implement `Movement` class
- [ ] Implement abstract `Interaction` class
- [ ] Implement children of `Interaction` class
- [ ] Finish testing `Task` class children
 
**Completion Deadline:** Tuesday, Week 5 (August 24th)
 
# **Documentation**
- A wiki page detailing the `Task` class and associated children will be created
- A javadoc detailing the `Task` class and associated children will be created
 
# **Members**
To be decided
