### ISSUE TITLE
Refine Buildings

### ISSUE THREAD

**Issue by Abishtu** [UQdeco2800/2022-studio-3#250]
# **Description**
**Task:** Refine Buildings.
**Feature:** #223 

Updating buildings from sprint 3 with new textures, animations and necessary component. Including implanting `Precise Isometric Entity Scaling and Placement` by team 6

# **Dependencies**
- [x] Completed sprite designs

# **Milestones**
List of steps that need to be completed for this task.
- [x] Adding new sprites
- [x] Adding missing components (if any)
- [x] Using new texture placement methods
 
# **Documentation**
- [Precise Isometric Entity Scaling and Placement](../wiki/Precise-Isometric-Entity-Scaling-and-Placement)
- [`TextureScaler`](https://uqdeco2800.github.io/2022-studio-3/com/deco2800/game/components/building/TextureScaler.html)
- ...
 
# **Member**
- Harikesha Suresh (@Abishtu)
- Zhiyuan Xu (@DLAmeng)
