### ISSUE TITLE
Inclusion of game over screen

### ISSUE THREAD

**Issue by prathammanocha** [UQdeco2800/2022-studio-3#258]
# **Description**
**Task:** Displaying the game over screen and linking a play again button.
A game over screen informs a user that the session of a certain level or game that they were playing has come to an end. It aids in keeping the game's instructions clear. This sprint we're going to link two buttons on the game over screen which would be:
1) Main Menu Button
- Takes the user back to main menu after the game ends.
2) Play Again
- Play again button, lets the user start the game over again.
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Linking the game over screen with an end game logic. (14 Oct)
- [ ] Creating an overlay for the buttons. (16 Oct)
- [ ] Making the buttons on the end game screen working (17 Oct)

**Completion Deadline:** 17th October
 
# **Member**
- Pratham Manocha (@prathammanocha ) (Pratham Manocha)

**Comment by prathammanocha** [comment]
https://github.com/UQdeco2800/2022-studio-3/commit/0b8f592fd38bf663ad6926433beb930a8dbd5480
