### ISSUE TITLE
Team 7 - Sprint 4 - Improve Map Flooding 

### ISSUE THREAD

**Issue by quocdat402** [UQdeco2800/2022-studio-3#259]
# **Description**
**Task:** [Improve Map Flooding](#3).
**Feature:** [Refine and Improve Map Flooding and Enemy Movement](#216)

The improvement for flooding feature are as follow:
* The resources will be disposed when that area is flooded.
* Add wave animation to the flooding tiles.
* Flash the next tile to be flooded few seconds before it got flooded.
* Make unit can no longer walk on the flooded areas of the map.
* Make floodind only happens from far left or right of the map instead of uniformly around the map.
 
## **Example**
* Friendlies cannot walk on the water area if it is flooded. As well as enemy types who only can walk on land.
* Dispose area of movement after the flooding.
 
# **Milestones**
- [ ] Flooding animation with waves (Oct 13)
- [ ] Resource disposal when flooded (Oct 13)
- [ ] Flash next tiles few seconds before being flooded (Oct 13)
- [ ] Make friendly units unable to go to the flooded area (Oct 13)
 
**Completion Deadline:** Oct 17

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
