### ISSUE TITLE
Polish of map and building

### ISSUE THREAD

**Issue by Fengqi0822** [UQdeco2800/2022-studio-3#261]
# **Description**
**Task:** [Polish component of map](#3).
**Feature:** [Fix some design problems and design some new components of city area](#2)

During this sprint, I am going to fix some original design problems. For example, the edge of the sand tile is irregular and the dimension of the sand and ocean is not the same. After that, I would like to design some new stuff to decorate the city area such as the water feature and so on. 

# **Dependencies**
City area and original design stuff
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Fix the sand edge 1 (Oct 7)
- [x] Design a new sand tile 2 (Oct 10)
- [x] Design a water feature 3 (Oct. 13)
- [x] User test 4 (Oct. 15)
 
**Completion Deadline:** Oct. 17
 
# **Documentation**
N/A
 
# **Member**
- Fengqi Yu (@Fengqi0822 ) (Fengqi Yu)
