### ISSUE TITLE
Fixing Semi-Select/Hover Highlighting and Sizing for Buildings

### ISSUE THREAD

**Issue by Akshath-K** [UQdeco2800/2022-studio-3#262]
# **Description**
**Task:** Semi-Select/Hovering Highlight (#3).
**Feature:** [Feature which this tasks contributes to implementing](#2)

As a part of our previous sprint, I was responsible for creating this effect and implementing it for units within the game, which included both static and moving objects (Buildings and Friendly Units).

But later on, a new team (6) took upon creating buildings and new buildings were made. So when testing the game I saw that the buildings had some sizing issue when selected or hovered over with the glow highlighting effect to be quite different then the rest of the game had. So,  in collaboration with team 6, I decided to contact them and ask permission if I can fix this issue. 

Luckily, they wanted to fix this problem for a long time and happily let me fix it. 
 
# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [ ] Team6Branch 
- [ ] Buildings Assets 
- [ ] SemiSelect

e.g.
- [ ] Fix highlighting
- [ ] Add correct amount of glow and outline.
- [ ] Fix sizing issue of buildings (resolution).
- [ ] Push the changes to Team6Branch. 
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1 (Oct.14)
- [ ] Step 2 (Oct. 14)
- [ ] Step 3 (Oct. 14)
- [ ] Step 4 (Oct. 14)
 
**Completion Deadline:** Oct. 14
 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Akshath (@Akshath-K ) (Akshath Katyal)
