### ISSUE TITLE
Initial Friendly Military Unit Implementation

### ISSUE THREAD

**Issue by HJPearce** [UQdeco2800/2022-studio-3#28]
# **Description**
**Task:** Adding an abstract class for entities which can 'participate in combat'.
**Feature:** This contributes to Structures, Enemies and Friendly Units

Abstract 'combatants' are entities that can be attacked, potentially attack (structures obviously will not attack) and 'die'. An entity has an overall attack and defence, along with a number of 'troops' which individually attack and are attacked (each with their own health). For now, we will say that structures are a unit that cannot attack, with one troop. Ranged troops will require additional characteristics in a class that extends the combatants.

This will be implemented by extending the CombatStatsComponent and adding it to an abstract combatant entity class
 
## **Examples**
-**Combatant example**: a spearman combatant may have 4 troops, 5 attack and 2 defence with each troop having 5 health.
- **Building Combatant example**: a Barracks will have 1 troop and 0 attack. It may have a defence of 1 and 30 health.

# **Dependencies**
This task has been created specifically to have no dependencies.
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Quick integration (Aug. 18)
- [x] Document in 'code wiki' create if not available.()
- [x] Make sure standard is adopted or corrected (Aug. 20)
 
**Completion Deadline:** Aug. 21

# **Documentation**
- [Code wiki](../wiki/code/Combatant) - does not yet exist
- [CombatStatsComponent JavaDoc](https://uqdeco2800.github.io/2022-studio-3/com/deco2800/game/components/CombatStatsComponent.html)
 
# **Member**
- Hayden Pearce (HJPearce)

**Comment by HJPearce** [comment]
Updated CombatStatsComponent, now need to create a unit as a grouping of troops (which will be the hard part)

**Comment by HJPearce** [comment]
Units still need to be spawned in a particular formation relative to one another which they move in, and this depends on the world transform (i.e. has a dependency on the map team feature integration). This and an attacking task will have to be completed in a further sprint due to the required integration. Note that movement bounds are currently hard set on an update, and in future, they should be done by having troops move relative to the entity centre, and move to their formation from the end of an attack task to an idle/move task.

For now this task is sort of finished

**Comment by HJPearce** [comment]
Also, I forgot to add, created grouping of troops in TroopContainerComponent and added a createExampleUnit in the UnitFactory
