### ISSUE TITLE
Intro Music and Menu Log Sound Effect

### ISSUE THREAD

**Issue by nhVietS** [UQdeco2800/2022-studio-3#29]
# **Description**
**Task:** [Intro Music Theme and Menu Log Sound Effect](#3).
**Feature:** [Sound and Background Music](#11)

A good intro music can help set the user/gamer mood before the game, help the game successfully get the first impression of the user and inspire them to engage with the further gameplay. The menu log sound is small effect to guide the user around menu UI.
 
## **Example**
- **Menu log sound effect**: Music plays when the game loads for the first time.
- **Background Music**: Background music playing in menu, and sound effects when menu units are clicked.

# **Dependencies**
- [x] The intro music will largely be based on the overall theme of the game and it's story(Game Story Comitee)
- [ ] The menu sound and music cannot be synchronized without a designed menu, however, the music can still be developed (#7)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Find some related music for inspiration  (Aug. 16)
- [x] Choose theme music (Aug. 18)
- [x] Compose or mix the music and make the first version of menu background music (Aug. 19)
- [ ] Create a music setting class (Aug. 21)
 
**Completion Deadline:** Aug. 22
 
# **Documentation**
- [Will update Wiki later](../wiki/Feature)
 
# **Member**
- Hoang Viet Nguyen (@nhVietS) Viet Nguyen
- Yashvardhan Batra (@yashvardhanbatra) Yashvardhan Batra
- Xinrui Tan (@Xanadu-james) Xinrui Tan
- Pratham Manocha (@prathammanocha) Pratham Manocha

**Comment by yobicakes** [comment]
Team 5 and Team 3 aimed to collaborate on a main menu page with sound play-ability and no merge conflicts. Task was accomplished, well done all!
