### ISSUE TITLE
Team-6 Sprint-1 Map Feature

### ISSUE THREAD

**Issue by kaitlyn-lake** [UQdeco2800/2022-studio-3#3]
# **Description**
We intend to develop all the core functionality pertaining to the game map, including the underlying class structures of game tiles and the means of generating the game map. Resources and island shape will be dynamically generated, whilst the city itself will be a static, consistent entity. This will allow variability between each playthrough, whilst not being completely overwhelming for a starting player. We will also create tools intended for use by other teams, such as a means to visualise a minimap, and a way to visualise map tiles on the main game screen.

## SubFeature/component (optional)
Top-down map design – map layout and tile placement design
Resource & tile entities – the entities/objects that the map will contain and will be generated
Static & procedural map generation – generate the map statically and randomly
Mini-map – displays and contains information about player position and map

## **Examples (optional)**
Class Design: developing the classes which represent tiles on the map. There should be an abstract class which will be able to determine the rest of the tiles objects. It is planned to have ‘dummy’ resource entities which may be valuable later such as mineable rocks which give one crystals to make another object. It is also planned to develop the connection between these object too. 

# **Dependencies**

No dependencies as this sprint is the original one and we will create dummy objects / tiles for future replacement. I.e., friendly and enemy units will be replaces with an entity class for future implementation. 

# **Milestones**
- [x] Rough design of the game map Goal 1 (Monday, Week 4)
- [x] Implemented a rudimentary generation algorithm Goal 2 (Wednesday, Week 4)
- [x] Integration of all map components Goal 3 (Monday, Week 5)
- [x] Polished and aesthetic final design of the game map Goal 4 (Wednesday, Week 5)

**Completion Deadline:** Aug. 29 – Monday week 6 (this is when the sprint is due in the ECP)

# **Extras (optional)**
Function/s that develop the visualisation of the tiles 
Isometric camera view of game
Ability to move camera with the mouse to pan around the entire map

# **Documentation**
– No user documentation is required until after the feature is completed
-- Eventually 2022-studio-3 game-engine wiki

# **Members**
Kaitlyn Lake (kaitlyn-lake) (Kaitlyn Lake)
Bailey Stoodley (BaileyS03) (Bailey Stoodley)
Max Jenkins (MaxJenko) (Max Jenkins)
Ryan (rjg1) (Ryan Gibbons)
Fengqi Yu (Fengqi0822) (Fengqi Yu)

**Comment by rjg1** [comment]
Extras related to camera viewing and movement added, as deemed critical aspects of viewing the map and playing the game
