### ISSUE TITLE
Team 1 Unit Selection task

### ISSUE THREAD

**Issue by JiashengLi** [UQdeco2800/2022-studio-3#30]
# **Description**
**Task:** Unit Selection Effect & Interaction
**Feature:** [Unit Selection Display/UI](#2)

We will build a function that prepares the selected target. When the player hovers over a legal target with the mouse (or hotkey), this feature will generate a highlight effect around the target to remind the user that the selection is ready for subsequent actions. 
At this node, no other interactions will take place.
 
## **Example (optional)**
- **Element**: When the mouse hovers over any legal target(buliding, worker, enemy), the edge of their model/illustration will generate special effects to alert the user.

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [ ] Friendly Units (Worker) (#5 )
- [ ] Friendly Units (Soldier) (#8 )
- [ ] Buildings  (#19 )
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Get research on implemention
- [ ] Having a way to select/deselect units/buildings in the game itself 
- [ ] UI/UX design for our games

**Completion Deadline:** Aug. 23

e.g.
- [ ] Initial design of `Armour` created and documented on wiki (Aug. 19).
- [ ] Unit tests implemented for `Armour` (Aug. 20).
- [ ] `Armour` class implemented and tested (Aug. 23).
- [ ] Documentation of `Armour` updated on wiki (Aug. 23).
 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
To be decided
