### ISSUE TITLE
Team 1 Unit Information Box task

### ISSUE THREAD

**Issue by JiashengLi** [UQdeco2800/2022-studio-3#31]
# **Description**
**Task:** Unit Information Box
**Feature:** [Unit Selection Display/UI](#2)

When the user confirms that the target is selected, we will have the game generate a box fixed in the corner to display the target's information.
The exact location and style of this box will be highly customizable based on the game's overall art style. Likewise, the information displayed in the box will vary based on the selected target category.
 
## **Example (optional)**
- **Building**: When a building is selected, its durability and upgrade materials may be displayed in the box, but never the movement speed.

# **Dependencies**
- [ ] Friendly Units (Worker) (#5 )
- [ ] Friendly Units (Soldier) (#8 )
- [ ] Buildings  (#19 )
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Get research on implemention
- [ ] Customize the display effect of different categories of goals

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
To be decided
