### ISSUE TITLE
Building placement system

### ISSUE THREAD

**Issue by hugh5** [UQdeco2800/2022-studio-3#33]
# **Description**
**Task:** [Building placement system](#33).
**Feature:** [Buildings Sprint 1](#19 )

The building placment system - when selecting a building to place, a transparent image of the building will follow the mouse around the map waiting for the player to select where to place the building. One placed, the building will become a physical obstacle in the game which the player can interact with

# **Dependencies**
- [ ] Coordinated with [Click to place building task](#32)
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] (Aug. 19) - Hovering over the map has opaque building image snapping to map grid
- [ ] (Aug. 22) - Places on the map when clicked
 
**Completion Deadline:** Aug. 22
 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Hugh Drummond (@hugh5)
- Angus Buchanan (@Spooey)
