### ISSUE TITLE
Team 9 - Rough animations and sprite batches for unit troops (Soldiers)

### ISSUE THREAD

**Issue by Harqua** [UQdeco2800/2022-studio-3#35]
# **Description**
**Task:** Creating rough animations as well as sprites for the unit troops
**Feature:** This contributes to any units, especially Soldiers and effectively ensures they match the Enemy and Worker units as well (#8, #12, #5 )

Different animations will be implemented to every unique unit depending on their specialities and type of movements.

## **Examples**
-**Archer**: The animations could include but are not limited to, aiming, shooting, and reloading the arrows.
-**Hoplites**: The animations could include but are not limited to, attacking, and blocking an attack.

# **Dependencies**
This task is dependent on matching the animation with the opposing troops (Enemy) (see #12 ), as well as other friendly units (see #5)
 
# **Milestones**
The list of troops needs to be animated.
- [x] Archers
- [x] Spearmen
- [ ] Pikemen (possibly removed)
- [x] Hoplites
- [x] Swordsmen
 
The task includes:
- [x] Creating sprites for the units
- [x] Animation for every movement and direction
- [x] Matching the design of the sprites with other teams

# **Documentation**
- [Units Home](https://github.com/UQdeco2800/2022-studio-3/wiki/Units-Home)
- [Animation](https://github.com/UQdeco2800/2022-studio-3/wiki/Animations)
 
# **Member**
- Garryco Thandi (Harqua)
- Yolanda Siruit (yolandawsiruit)

**Comment by HJPearce** [comment]
Oml why were none of these closed
