### ISSUE TITLE
Team 5 Create containers for Game UI 

### ISSUE THREAD

**Issue by alyshaziya** [UQdeco2800/2022-studio-3#36]
# **Description**
**Task:** [Resource Label/Game UI].
**Feature:** [Dynamic/Static UI](#7)

Implement the resource label for the game UI. This includes stats of all key game statistics such as the count of current resources, city health, troop/enemy count, a map display showing where the user is on the map, (unconfirmed) a switch action component which shows what mode the game is in (building mode or troops deploy mode). For this task, UI containers need to be made to house each of these components on the game screen. 

 
## **Example (optional)**
- **Map**: When the user moves around the map, you can see the current location relative to the map display component.
- **Resource**: Can see current resource count on game UI. 
- **Actions**: Can see selection action on game UI

# **Dependencies**
- [ ] Unit information box, integrate this feature into resource label UI (#31 )

# **Milestones**
List of steps that need to be completed for this task.
- [x] Finalise UI components, document UI (Aug. 22)
- [x] Create containers for UI components (Aug. 24)
- [x] Integrate art style (Aug. 29)
 
**Completion Deadline:** Aug. 30 (Wednesday Week 5)
 
# **Documentation**
- Will be added progressively as milestones are reached
 
# **Member**
- Alysha Ismail (@alyshaziya) (alysha ismail)
