### ISSUE TITLE
Team 5 - Sprint 1 - DialogueBox functionality

### ISSUE THREAD

**Issue by usrnatc** [UQdeco2800/2022-studio-3#37]
# **Description**
**Dialogue Box Functionality:** Creating dialogue boxes that are triggered by pseudorandom events
**Feature:** [MainUI functionality](#7)

After a dialogue box event is triggered, a dialogue box will show within the main gameUI and have the ability to:
 - if the shown text is overflown, the functionality to continue to the previously hidden text;
 - be dismissible entirely as to not disrupt gameplay flow
 
## **Example**
- **Low bubble health**: When the bubble is about to be destroyed and the player is thus about to lose, a dialogue box will appear to alert the player of the impending finale.
- **Task completion**: When friendly troops have finalised a task and the troops are not within the currently viewable game area, a dialogue box will appear to alert the player.

# **Dependencies**
The dialogue box functionality will be generalised such that its integration requires no dependencies. This allows for easier and simpler future feature implementation and integration
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Display dialogue box Friday (week 4)
- [x] trigger dialogue box through event Saturday (week 4)
- [x] complete `scroll-text` and `dismiss` functionality Saturday (week 4)
- [ ]  ~~animate dialogue box Monday (week 5)~~
 
**Completion Deadline:** Monday (week 5)
 
# **Member**
- Nathan Corcoran (@usrnatc) Nathan
