### ISSUE TITLE
Team 4 - Ticket - Enemy AI

### ISSUE THREAD

**Issue by Abishtu** [UQdeco2800/2022-studio-3#38]
# **Description**
**Task:** AI
**Feature:** #12 

This task involves anything to do with enemy AI, this will include
* Combat (parts of this might be completed in #24)
* Movement
* _Field of View_
 
## **Example (optional)**
- **Movement**: Ghouls will move in a certain path compared to demons, since they're smaller they might opt to rush at the enemy and engage in close combat, whilst demon will opt to go slower and deal heavy attacks.
- **Field of View**: What's gonna happen once friendly units enter into the enemies field of view, how will they respond, will that response change depending on unit type?
- **Ranged Attack**: When the player's unit enters the attack range of a remote enemy, the enemy will fire bullets.

# **Dependencies**
- [x] Path finding for AI #14 
 
# **Milestones**
- [x] Movement (Aug. 23)
- [x] Combat, Ranged attack (Aug. 25)

# **Optional**
- [x] Field of View (Aug, 28) 

**Completion Deadline:** Aug. 30
 
# **Documentation**
_To be decided by assigned members_

# **Member**
- Jun Utsunomiya (@JunUtsunomiya)
- Zhiyuan Xu (@DLAmeng)
