### ISSUE TITLE
Building art design

### ISSUE THREAD

**Issue by WW7796332** [UQdeco2800/2022-studio-3#41]
# **Description**
**Task:** Town hall and walls art design
**Feature:** [[Team-2 Sprint-1 Structures/Buildings]](https://github.com/UQdeco2800/2022-studio-3/issues/19#issue-1338531834)(#19 )

The art style of all buildings should be Atlantean style. Different kinds of walls have different defense levels, and the higher the level of the wall, the higher its health value.
 

# **Dependencies**
- [ ] https://github.com/UQdeco2800/2022-studio-3/issues/18#issue-1338400956(#18 )Art design of building depends on map construction.
 
# **Milestones**
- [ ] Complete the line drawing design of the town hall(Aug. 19)
- [ ] Complete the coloring of the town hall (Aug. 20)
- [ ] Designing different kinds of walls (Aug. 23)
- [ ] Planning the level of the walls(Aug. 23)
 
**Completion Deadline:** Aug. 23

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
 
# **Member**
- Wenfeng (WW7796332) (Wenfeng Wang)
