### ISSUE TITLE
building art design

### ISSUE THREAD

**Issue by nicococole** [UQdeco2800/2022-studio-3#42]
# **Description**
**Task:** [Mining camp](#3).
**Feature:** [Building](#2)

There will be a lot of resources in mining camp, the player can search and obtain material in this place.
A certain resources here can increase health. When the layer's health is less than 100 because of damage, people can be treated by this resources.

# **Dependencies**
- [ ] Mining camp needs to be created for armour laying on map.
- [ ] Need resources
 
# **Milestones**
- [ ] Initial design of `Mining camp` created and documented on wiki (Aug. 19).
- [ ] Unit tests implemented for `Mining camp` (Aug. 20).
- [ ] `Mining camp` class implemented and tested (Aug. 23).
- [ ] Documentation of `Mining camp` updated on wiki (Aug. 23).
 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [Mining camp](JavaDoc/Location/Package/Class)

 
# **Member**
- Wenjing Shan(@nicococole)
