### ISSUE TITLE
Random Events Art Design

### ISSUE THREAD

**Issue by lijunyao1** [UQdeco2800/2022-studio-3#43]
# **Description**
**Task:** [Random event art design]().
**Feature:** [Team 7 - Random Event Generator Feature](#6)

The design of random event generator included weather signs, item and item signs and augment choices design.
 
## **Example (optional)**
- **Random items art design**: An iron trident and a gold trident. Tridents will fall when enemies died.
- **Narrative choice art design**: For narrative choices, users can select different augments to decide the game progress.

# **Dependencies**

- Random weather effect based on Friendly units features. (#5), (#8)
- Narrative choice effect based on Friendly units features. (#5), (#8)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Weather signs design (Aug. 21)
- [x] Random items design (Aug. 21)
- [x] Narrative choice design (Aug. 25)
 
**Completion Deadline:** Aug. 25
 
# **Documentation**
- [Main description of Random Event Art Design](https://github.com/UQdeco2800/2022-studio-3/wiki/Random-Events-Design)
 
# **Member**
- Junyao LI (lijunyao1) (Junyao Li)
