### ISSUE TITLE
Implementation of base viewing tools and gameplay functionality

### ISSUE THREAD

**Issue by rjg1** [UQdeco2800/2022-studio-3#47]
# **Description**
**Task:** [Base gameplay functionality](#3).
**Feature:** [Team-6 Sprint-1 Map Feature](#2)

This ticket refers to the implementation of the map-based elements developed by team 6 into the game engine itself. It includes: 
- The visualisation of the randomly generated map as tiles
- The ability to pan the camera around the map by moving the mouse to the edge of the screen
- Creating obstacles around the island and the map itself to keep the player in
- Limiting the camera's movement to within the gameplay area
- Allowing the camera to zoom
 
## **Example**
- **Vision for features implemented in Sprint 1**: Player loads into game. Island is dynamically generated and visualised as terrain. The allied units spawn in the centre of the city and the camera centres on them. Players cannot move off the island or off the map due to instantiated boundaries. The camera may be freely panned around the island by hovering the mouse towards that edge, but it is restricted from panning off the edge of the map. The camera may be zoomed to widen the view.

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [x] Dynamic map generation (#3)
- [x] Tile sprite development (#3)

e.g.
- [x] Ocean/Island textures need to be created for proper implementation
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Have map viewable in isometric, with obstacles around the island and a movable camera (Aug. 20)
- [x] Stop camera on boundaries of map (Aug. 21)
- [x] Add camera zoom in/out (Aug. 23)
- [x] Adapt functions relying on tile size when map is zoomed (Aug 23)
 
**Completion Deadline:** Aug. 23

# **Documentation**
- Documentation of new classes created on the wiki
 
# **Member**
- Ryan (rjg1) (Ryan Gibbons)
