### ISSUE TITLE
Implement Time-based Weather Events

### ISSUE THREAD

**Issue by Corfliss** [UQdeco2800/2022-studio-3#48]
# **Description**
**Task:** Time-based Event Generator
**Feature:** [Random Event Generator](#6)

After making the PRNG, an idea to implement the time-based weather event is implemented. This will include a random interval time and an event to make.
 
## **Example**
* After x minutes, the weather is changing, and then y minutes later it changed again, and so on. x and y is a random number from a finite interval.

# **Dependencies**
Currently there are no dependecies
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Make a timer for random mechanics for the weather
- [x] Make interruption to the game time.
- [x] Displaying the weather
- [x] Changing the weather
 
**Completion Deadline:** Aug. 28
 
# **Documentation**
- To be added.
 
# **Member**
- Fauzan Hanandito Chaidir (Corfliss)
- Haozhe Ding (RichardD02)
