### ISSUE TITLE
Team 5- Main Menu functionality

### ISSUE THREAD

**Issue by yobicakes** [UQdeco2800/2022-studio-3#50]
# **Description**
**Task:** [Main Menu](#3).
**Feature:** [Dynamic/Static UI functionality](#2)

The main menu is the user's first interaction with the game, it contains: 
- a start button that initializes game play
- a static background relevant to the game 
- basic sound that established the mood
 
## **Example**
- **Main Menu**: The game engine will display the main menu with a background image and basic sound. The user may choose to "Start Game" which initializes the cut scene which, in turn, initializes game play. 

# **Dependencies**
- [x] Menu sound design will rely on the sound design team (Team 3)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Establish prototype of basic menu (25 Aug.)
- [x] Finalise UI of menu (25 Aug.)
- [x] Sound Playability (25 Aug.)
- [x] Background image design- art style (25 Aug.)
 
**Completion Deadline:** Wednesday, Week 5

# **Member**
- Neha Tewari (@yobicakes ) (Neha Tewari)

**Comment by nhVietS** [comment]
Team 3 is responsible to deliver an intro song, which should not causing any merge conflicts. Task done successfully.
