### ISSUE TITLE
Team 5 - sprint 1 - Pause Menu functionality

### ISSUE THREAD

**Issue by Suuoooooooo** [UQdeco2800/2022-studio-3#52]
# **Description**
**Task:** [Pause menu functionality].
**Feature:** [Dynamic/Static UI](#7)

Implement pause menu and cut scene features for the game UI. Pause menu feature includes freezing the current game and displaying options for player to resume the game, go to settings or quit the game. Cut scene feature includes displaying a text box with rolling text inside and background image visualization.

# **Dependencies**
- [ ] Cut sences should have BGM(#11)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Finalise background images for cut scenes(Aug. 25)
- [x] Overlay text box with background images (Aug. 27)
- [x] Implement pause menu(Aug. 28)
- [x] Integrate art style (Aug. 29)
 
**Completion Deadline:** Aug. 30 (Wednesday Week 6)
 
# **Documentation**
- Will be added in the future patches.
 
# **Member**
- Tiansong Zhang (@Suuoooooooo) (Tyrion Zhang)
