### ISSUE TITLE
Integrate Intro Song

### ISSUE THREAD

**Issue by nhVietS** [UQdeco2800/2022-studio-3#53]

**Comment by nhVietS** [comment]
# **Description**
**Task:** [Integrate Intro Song to Main Game Menu](#3).
**Feature:** [Sound and Background Music](#11)

A good intro music can help set the user/gamer mood before the game, help the game successfully get the first impression of the user and inspire them to engage with the further gameplay. 
 
## **Example**
- **Background Music**: Background music playing in menu.

# **Dependencies**
- [ ] The menu sound and music cannot be synchronized without a designed menu, however, the music can still be developed (#7)
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Create a song with theme music. Put song to core.assests.sounds (Aug. 18)
- [ ] Integrate with these functions in MainMenuScreen file (Aug. 19)
- [ ] Build and Run Unit test and ask User test(Aug. 28)
- [ ] Documentation of Intro Song(Aug. 28)
 
**Completion Deadline:** Aug. 29
 
# **Documentation**
- [Will update Wiki later](../wiki/Feature)
 
# **Member**
- Hoang Viet Nguyen (@nhVietS) Viet Nguyen
