### ISSUE TITLE
Team 7 - Sprint 1 - Random Event Generator Feature

### ISSUE THREAD

**Issue by Corfliss** [UQdeco2800/2022-studio-3#6]
# **Description**
Implement a random event generator feature, which the name suggests, is about making events that might be helpful to players or not. We do this to add unpredictability to the game in order to make it more engaging. For example, like how a feature in the game such as building is damaged due to flooding and unable to operate, or if there is a person who needs help from the sinking place. In the final product, it will be making a procedurally-generated event that will advantage or disadvantage the player while also keeping the game balanced.

## SubFeature/component (optional)
* Map-based random generated event: can be about different area of flooding or certain area hit by a thunderstorm.
* Random weather generation: can make the sinking faster or slower depending on the weather.
* Item randomizer: when you find something that will help or not help the progression of the game.
* Narrative choice: to decide the game progress based on player's choice.

## **Examples (optional)**
* Random thunderstorm/rain/earthquake struck a building due to random generated events.
* A civilian might come to you for asking help for another person, that might help or slow the progress of the game.
* One of your unit found a random interesting item to help or slow the progress of the game.

# **Dependencies**
The random generated event feature depends on the map feature ( #3 ), friendly/enemy units feature (unassigned), and building feature (unassigned). 

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Goal 1: Decide on which random events design to be created for this sprint (Aug. 20)
- [x] Goal 2: Implement the inital random generator (Aug. 28)
- [x] Goal 3: Design art of the random event (Aug. 28)
- [x] Goal 4: Finalize the initial design and implementation of the random event generator (Aug. 29)

**Completion Deadline:**
Aug. 29

# **Extras (optional)**
So far we don't have any extras to be added.

# **Documentation**
No documentation is required for now until the feature is completed.

# **Members**
- Name (GitHub Username) (Slack Handle) -- only one is needed if they are the same.
- Junyao Li (@lijunyao1) (Junyao Li)
- Fauzan Hanandito Chaidir (@Corfliss)
- Quoc Dat Mai (@quocdat402) (Dat Mai)
- Haozhe Ding (@RichardD02) (Haozhe Ding)
- Jordan Brewis Foulger (@jordanlbf)
