### ISSUE TITLE
Team 1 Selecting Units Task

### ISSUE THREAD

**Issue by Sourav-RC** [UQdeco2800/2022-studio-3#62]
# **Description**
**Task:** [Selection of unit(s)]
**Feature:** (Unit Selection Display/UI) (#2 )

One of the key points of an RTS game is to be able to interact with things on the screen. Most notably, the ability to select characters and buildings on the screen to get additional information on their current state.
 
## **Example (optional)**
- **Select**: When a building or character is selected, they are highlighted in some way to let the player know that the unit has been selected. 

# **Dependencies**
Selectable units

- [ ] Friendly Units (Worker) (#5)
- [ ] Friendly Units (Soldier) (#8)
- [ ] Enemy Units (#12)
- [ ] Buildings (#19) 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Identification of selectable units
- [x] Indicator that unit is selectable (change cursor)
- [x] Highlighting the unit when the unit is selected
- [x] Displaying a pop-up box
- [x] Displaying information of selected unit on pop-up box 

 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Sourav (@Sourav-RC ) (Sourav Roy Chowdhury)

**Comment by Sourav-RC** [comment]
Done
