### ISSUE TITLE
Team 5 - Sprint 1 - Dynamic/Static UI Functionality

### ISSUE THREAD

**Issue by usrnatc** [UQdeco2800/2022-studio-3#7]
# **Description**
We will create the main menu functionality, in-game pause menu, and initial cut scene functionality for the game. This will also include dialogue-box events that will be encountered randomly. Resource labels during in-game playing.

## SubFeature/component
Main Menu:
 - start game functionality
 - end game functionality
 - static background image
 - basic sound playability

Pause Menu:
- restart game functionality

Cutscene:
- display full-screen image
- dialogue box showing story throughout
- basic sound playability

Dialogue Boxes:
 - show small window spanning width of screen and displaying basic text and sprites
 - ability to be triggered at any 'playing' state of game

Resource Labels:
 - show current game statistics throughout gameplay

## **Example Logic**
 - The game will run as a finite series of states:
    - ready-state: game is in the initial menu and has not been played yet
    - playing-state: game is currently being played and is not paused
    - paused-state: game is currently being played and is paused
 - This would allow for dialogue boxes and other random events to only happen when the game is currently in a playing-state.
# **Dependencies**
 - Menu art style will rely on the map design team
 - Menu sound design will rely on the sound design team
 - Dialogue box art style will rely on the map design team
 - Cutscene content will rely on game story team

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Main Menu functionality (Wednesday week 5)
- [ ] Pause Menu functionality (Wednesday week 5)
- [ ] Dialogue Box functionality (Wednesday week 5)
- [ ] Resource label display (Wednesday week 5)

**Completion Deadline:** Monday week 6

# **Documentation**
- Documentation will be added after functionality is added and in a working state

# **Members**
- Nathan (@usrnatc) (Nathan Corcoran)
