### ISSUE TITLE
Team 1 Sprint 2 Feature Ticket

### ISSUE THREAD

**Issue by JiashengLi** [UQdeco2800/2022-studio-3#76]
# **Description**

_To be edited_
In sprint 2, we're going to publish the detailed the interaction of the box...
While a Legal Target is selected, more status will shown..
The special status, which is the health, may shown as a health bar..
The box may only appear while a unit is selected and hide itself everytime else to clear the game UI...

## **Examples**

- Examples for semi-selection
- Examples for dynamic status
- Examples on health bar
- Information Box only appears upon click and disappears when pressed ESC or clicked anywhere outside the box.

- **Legal Targets**: Generally speaking, legal targets include buildings, creatures, and resource points. This range will change as the game is further developed.

# **Dependencies**

- **The layout of the information box**: This element needs to occupy a part of the area  in the overall UI construction (#xxxx).

- **Buildings, Enemies and Friendly Creatures**: This feature must select the generated objects to get their variables and properties for display (#xxxx).

# **Milestones**

- [x] Goal 1: Come up with a UI display of the selected unit/building(drawn out) (Aug. 20)
- [x] Goal 2:  Having a way to select/deselect units/buildings in the game itself(Aug. 23)
- [x] Goal 3:  Replicate the UI display box we have drawn out into the game itself (Aug. 26)
- [x] Goal 4: Link selecting different types of units to the respective display boxes in the game itself (Aug. 28)

**Completion Deadline:** Aug. 30

# **Extras (optional)**
- [ ] When hovering over a building, have an outline of the building.

# **Documentation**

- ...(The later Wiki documentation)

# **Members**
- Jackie (@jackieooikk ) (Jackie Ooi)
- Akshath (@Akshath-K) (Akshath Katyal)
- Lee (@JiashengLi) (Jiasheng Li)
- Kawhi(@jiupinbaocha )(Yi Yu)
- Sourav (@Sourav-RC) (Sourav Roy Chowdhury)
