### ISSUE TITLE
Team 7 - Sprint 2 - Weather Effect Visual Representation

### ISSUE THREAD

**Issue by quocdat402** [UQdeco2800/2022-studio-3#78]
# **Description**
**Task:** [Weather Effect Visual Representation].
**Feature:** [Random Events Generator Continued](#92)

Extend functionality of randomly generated weather icons by mapping a weather type to an aesthetic and proper colour scheme (i.e., a filter)
 
## **Example**
- When the weather is thunderstorm, lighting effect might change to dark and will appear some flash animation in the screen.
- When the weather is sunny, the enviroment should be vibrant and sunny

## **Dependencies**
- (#91)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Display the filter to the game source code
- [x] Code the animation for the filter to the game
- [x] Debugging the code if exists
 
**Completion Deadline:** Sep 6

# **Documentation**
- Wiki will be added later.
 
# **Member**
To be added later.
