### ISSUE TITLE
Team-9 Sprint-1 Friendly Units (Soldiers) Feature

### ISSUE THREAD

**Issue by HJPearce** [UQdeco2800/2022-studio-3#8]
# **Description**
This ticket covers all of the stylings and internal mechanics of friendly military units. This will include how the player controls them, how they move and fight, and likely matters of their cost and the resource economy in battle (though this heavily overlaps with #5 and the production of resources).

## SubFeatures/components
- Units must be selectable and manageable (can be deleted etc.)
- Units must be able to navigate (this overlaps with Enemies (add ticket no. once created)), including swimming through water or moving to/from boats if applicable (use of boats is unclear)
- Units must be able to fight enemies (for testing it may be sufficient to have the same units fight each other on opposite 'teams') corresponding to their MSP.
- Obviously, each unit type will require a set of sprites and animations for moving, fighting, etc.
- Units must be producible from a corresponding 'base building' (this requires collaboration with the structures/buildings team (add ticket no. when assigned))
- Units must have an independent level statistics that increments based off of on a level system  
- Hoplite: First ranks of unit trained to execute and attack enemy units.
- Phalanx: They present shields and are only for defensive strategy, not offensive. 

## **Examples**
- **Unit structure**: Units will each be produced by a building, contain a certain number of 'troops'; have an attack, defence and internal health for each troop (morale?). Ranged troops will have a range and either simulated/semi-random animated projectiles for attacks
- **Unit example**: an archer unit may have 7 troops, 5 attack and 3 defence with a range of 3 tiles, produced from a barracks with each troop having 5 health; They may also have a ground movement of 5 and swimming movement of 2

# **Dependencies**

- The movements of the soldiers need to match the enemy
- Swimming/navigation requires at least the model of a map (see #3)
- fighting will likely need to be randomly seeded (potentially relying on #6 if generation source is shared)
- 'Base building' where the units will be produced (team 2)
- Initial unit generation when the player makes a selection (see #2 )

e.g. Random game mode relies on random map seed generation(#xx).

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Generate a rough outline of unit generation. (including stat levels) . (Aug. 20)
- [x] Implement individual entities or factories for each unit type. (Aug. 24)
- [x] Design unit stats UI  (Aug. 26)
- [x] Have rough animations and sprite batches for unit troops (Aug. 28)
- [x] Implement unit generation. (Aug. 28)

**Completion Deadline:** Aug. 30

# **Extras (optional)**
- [ ] Projectiles for ranged units
- [ ] Diving/3d water traversal

# **Documentation**
- [Unit selection](../wiki/Unit-Selection)
- [Units listing and characteristics](../wiki/Units-Home)

# **Members**
- Name (GitHub Username) (Slack Handle) -- only one is needed if they are the same.
- Hayden Pearce (HJPearce) (name)
- Garryco Thandi (Harqua) (Garry Th)
- Mehr Chawla (Mehr)
- Li-Chuan Yeh (Daniel)
- Yolanda Sirait (yolandawsirait)

**Comment by HJPearce** [comment]
Submitted this for editing - not ready for approval yet

**Comment by HJPearce** [comment]
This should've been closed a while ago
