### ISSUE TITLE
Team 6 sprint 2: Map feature continued

### ISSUE THREAD

**Issue by kaitlyn-lake** [UQdeco2800/2022-studio-3#80]
# **Description**
This will be a continuation of the feature begun in Sprint 1. This will include an internal map representation that will be accessibly by other feature teams to coordinate entity position and path finding on the map, animation to the terrain environment, dynamic resource generation and a final polished front end mini-map and map design. The internal map will be implemented as a global feature accessible through ServiceLocator.

## SubFeature/component (optional)

- Internal map representation
- Integration of internal map representation with entity creation teams
- Display entities on the minimap
- Dynamic resource generation
- Texture generation on minimap

## **Examples (optional)**

- **Internal map representation**: worker and enemy unit feature teams can register their units with the MapService by adding a MapComponent to the entity. They can then access the map by calling ServiceLocator.getMapService(), through which they can check where other entities are in the game, whether a tile is occupied, and potentially a shortest path between two points in the map.
- **Minimap**: rendered in the bottom right corner with textures corresponding to the terrain or entity at that position in the game. As entities move, it dynamically updates to render their new position
- **Dynamic resource generation**: On game start, desired resources will be generated at random positions based on set criteria i.e., some resources may spawn further from the city or vice versa. It will be expandable to spawn any number of resources at any range of quantities.

# **Dependencies**

Will be updated progressively.

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Have polished functioning internal map representation (Sep. 5)
- [ ] Have entities displayable on minimap (Sep. 5)
- [ ] Integrate internal map structure with other team features (Sep. 7)
- [ ] Dynamic resource generation (Sep. 8)
- [ ] Minimap texture generation (Sep. 9)
- [ ] Terrain animation (Sep. 10)
- [ ] Unit tested feature (September. 11)

**Completion Deadline:** 13 September

# **Extras (optional)**
- [ ] Flooding functionality

# **Documentation**

To be created.

# **Members**

- Max Jenkins (@MaxJenko) (Max Jenkins)
- Fengqi Yu(@Fengqi0822) (Fengqi Yu)
- Ryan Gibbons (@rjg1)
- Kaitlyn Lake (@kaitlyn-lake) (Kaitlyn Lake)
