### ISSUE TITLE
Enhanced Minimap Functionality - Sprint 2

### ISSUE THREAD

**Issue by rjg1** [UQdeco2800/2022-studio-3#82]
# **Description**
**Task:** Enhanced Minimap Functionality(#3).
**Feature:** [Team 6 Sprint 2  - Map Continued](#80 )

Currently the ingame Minimap only renders the game terrain and the field of view with rectangles of static colour. This task proposes an overhaul to the minimap, allowing it to continuously render game entities with specific textures designed for the map. This provides significant benefit, as it allows the player to accurately track the flow of the game.
 
## **Example (optional)**
- **Player experience**: When a player loads into the game, they will see a visually pleasant map in the bottom right corner of the screen, they will be able to track allies and entities as they move, and easily view the layout of the city.

# **Dependencies**
- [ ] Textures being developed for the minimap(#xx)
- [ ] Internal map representation of the game(#xx)
- [ ] 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1 visualise internal map of game (Sep 5)
- [ ] Step 2 visualise designed textures in place of coloured squares (Sep 12)
 
**Completion Deadline:** Sep 13

# **Documentation**
- Expansion of wiki article on the MinimapComponent to reflect the changes this Sprint
- Javadoc comments
 
# **Member**
- Ryan Gibbons (rjg1)
