### ISSUE TITLE
Team 6: Internal map representation

### ISSUE THREAD

**Issue by kaitlyn-lake** [UQdeco2800/2022-studio-3#83]
# **Description**
**Task:** [Internal map representation](#3).
**Feature:** [Team 6 sprint 2: Map feature continued](#80)

This task will implement an internal map structure to manage entity positions in the map and pathfinding. It will facilitate integration of entity features developed by other teams into the game. The internal map will be implemented as a global feature accessible through ServiceLocator.
 
## **Example (optional)**

- **Internal map representation**: worker and enemy unit feature teams can register their units with the MapService by adding a MapComponent to the entity. They can then access the map by calling ServiceLocator.getMapService(), through which they can check where other entities are in the game, whether a tile is occupied, and potentially a shortest path between two points in the map.

# **Dependencies**

- [x] Pathfinding implementations (#16)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Implement an internal map feature (Sep 5)
- [x] Integrated map with other team features (Sep 7)
- [x] Polished unit tested version (Sep 9)
- [x] Wiki document feature (Sep 10)
 
**Completion Deadline:** Sep. 13
 
# **Documentation**

To be created.
 
# **Member**

- Kaitlyn Lake (@kaitlyn-lake) (Kaitlyn Lake)
