### ISSUE TITLE
Dynamic Resource Generation

### ISSUE THREAD

**Issue by rjg1** [UQdeco2800/2022-studio-3#84]
# **Description**
**Task:** Dynamic Resource Generation(#3).
**Feature:** [Team 6 Sprint 2  - Map Continued](#80)

As resources are critical to gameplay in terms of creating and upgrading units or winning the game, their placement is essential to maintaining the strategy component of the game. This feature will implement an algorithm that will procedurally spawn resources in a desired quantity at key locations in the island - promoting a unique experience with each game, while still being sufficiently restrictive to not have too much variance.
 
## **Example (optional)**
- **Player experience**: Upon loading into the game, the player will be able to explore the island they are placed on to resources relevant to game participation and completion

# **Dependencies**
- [x] Procedural Map Generation

# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 Write class to hold Resource Specifications (Sep 5)
- [x] Step 2 Write class to generate Resources based on resource specifications (Sep 5)
- [x] Step 3 Implement spawning the resources at their appropriate location in game (Sep 12)
 
**Completion Deadline:** Sep 13

# **Documentation**
- Expansion of wiki article on the MapGenerator to reflect the changes this Sprint
- Javadoc comments
 
# **Member**
- Ryan Gibbons (rjg1)
