### ISSUE TITLE
Team 6 - design of map

### ISSUE THREAD

**Issue by Fengqi0822** [UQdeco2800/2022-studio-3#85]
# **Description**
**Task:** [Creating animate of component of map](#3).
**Feature:** [Animate of map](#2)

Implement the animation of ocean waves and rock and trees. The way to implement animation is to make a bunch of different states of the ocean and an atlas file to let the program catch the image of the ocean to form the animation. For the tree and the rock, add more details to them and let them more vivid. 
 
## **Example (optional)**
- **Component of Map**: Players can see the wave of the ocean and the vivid trees and rocks.

# **Dependencies**
The original design of the ocean, tree and rocks
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1  New tree design (Sep. 2)
- [x] Step 2 New rocks design (Sep. 4)
- [x] Step 3 Wave of the ocean (Sep. 10)
- [x] Step 4 Finish the animated tile on map(Sep. 11)
- [x] Step 5 User research  (Sep. 13)
 
**Completion Deadline:** Sep. 13
 
# **Documentation**

# **Member**
- Fengqi Yu(@Fengqi0822) (Fengqi Yu)
