### ISSUE TITLE
Team 9 sprint 2: Soldiers feature continued 

### ISSUE THREAD

**Issue by Mehr-creates** [UQdeco2800/2022-studio-3#86]
# **Description**
This ticket serves as continuation to the sprint 1 and additional functionality for the same. This will include how the player controls them, how they move and fight, and likely matters of their cost and the resource economy in battle (though this heavily overlaps with https://github.com/UQdeco2800/2022-studio-3/issues/5 and the production of resources). This sprint will mainly focus on getting the units in the game and having them move around. The functionality could include attacks and stat monitoring.

## SubFeature/component (optional)
- Units must be selectable and manageable (can be deleted etc.)
- Units must be able to navigate, including swimming through water or moving to/from boats if applicable (use of boats is unclear)
-  Each unit should have corresponding factories and will be of four types: archer, swordsman, spearman, hoplite.
-  Units type of unit can initiate their corresponding attacks.
-  Units should have a health bar and corresponding stats on the basis of their assignment. 
- Unit should avoid collisions with buildings.
-  Change intro music to suit game theme, add code to mute music in `MainMenuScreen`
-  Compose background music for the gameplay in `AtlantisGameArea`
-  Make sound effect of friendly units

# **Dependencies**
- The movements of the soldiers need to match the enemy
- Stats need to be balanced between enemies and soldiers
- Navigation requires at least the model of a map (see https://github.com/UQdeco2800/2022-studio-3/issues/3)
fighting will likely need to be randomly seeded (potentially relying on https://github.com/UQdeco2800/2022-studio-3/issues/6 if generation source is shared)
- 'Base building' where the units will be produced (team 2)
- Initial unit generation when the player makes a selection (see Team 1 feature ticket (Sprint 1) - Unit Selection Display/UI  #2 )
e.g. Random game mode relies on random map seed generation(#xx).
- Health bar of the unit and the stats (team 1)
- MainMenuScreen UI for mute button in team 5

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Factories for individual units: archer, hoplite, spearman, swordsman(Sept. 2)
- [ ] Create another version of intro music(Sep 2)
- [ ] Create sound effect of friendly units(Sep 2)
- [x] Compose draft of background music(Sep 3)
- [ ] Do user test of the music, sound effect(Sep 6)
- [x] Spawning the units and their navigation (Sept 6)
- [ ] Edit and Release final draft of music, sound effect base on User test(Sep 9)
- [x] Integrate assets of music and sound to code(Sep 10)
- [x] Updating the sprite sheets for all soldier units to get them implemented
- [x] #93 (Optional, might be done for sprint 3 or by other teams)

**Completion Deadline:** Sept. 13

# **Members**
- Mehr-Creates (mehr)
- Harqua (Garryco Thandi)
- Hoang Viet Nguyen (@nhVietS) Hoang Viet Nguyen
- yolandawsirait (Yolanda Sirait)

**Comment by HJPearce** [comment]
Smh can't believe this wasn't closed
