### ISSUE TITLE
Team 5- Sprint 2- Advanced Dynamic/Static UI

### ISSUE THREAD

**Issue by yobicakes** [UQdeco2800/2022-studio-3#87]
# **Description**
We will build from the funtionality implemented for Sprint 1 and tie up any loose ends/ unpresendented bugs in the code. Our main goals are: implementing cutscenes, dynamic resizing, changing button skins, including icons in the resource labels, stopping the camera for the pause menu, creating more robust dialogue boxes. If time permits, we may also build an in-game tutorial and a mute button to stop the music.

## SubFeature/component (optional)
Cutscenes:
- Full screen Image
- Finalizing cutscene image designs 
- Story Text
- Basic sound
- Dynamic transition between images

Buttons: 
- Finalizing button skin designs
- Replacing text button with images

Pause Menu:
- Stops map movement and game play when clicked on 

Dynamic resizing:
- Resizing images/ dialogue boxes/ buttons and resource labels to fit game screen

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Cutscenes (Sep. 9)
- [x] Buttons (Sep. 9)
- [x] Pause Menu (Sep. 9)
- [x] Dynamic Resizing (Sep. 9)
- [x] Resource Label Icons (Sep. 9)

**Completion Deadline:** Sep. 12 2022

# **Extras (optional)**
- [ ] In game tutorial (shows basic game play)
- [ ] Mute button (Mutes music)

# **Documentation**
Documentation to be added after implementation of task tickets

# **Members**
- Nathan (@usrnatc ) (Nathan Corcoran)
- Alysha (@alyshaziya ) (Alysha Ismail)
- Tyrion (@Suuoooooooo  ) (Tiansong Zhang)
- Neha (@yobicakes ) (Neha Tewari)
- Pratham (@prathammanocha) (Pratham Manocha)
