### ISSUE TITLE
Buildings spawn for the city

### ISSUE THREAD

**Issue by hugh5** [UQdeco2800/2022-studio-3#90]
# **Description**
**Task:** [Buildings spawn for the city](#90).
**Feature:** Advanced Buildings and Structures

This feature involves spawning all the builings and structures into the city in the map so the player has somewhere to explore and buildings to interact with. This will mostly be done in the game area. When spawning buildings, register with the map which tiles they take up for other features that need the positions of these buildings (e.g. pathfinding).

# **Dependencies**
Relies on 
- [ ] [Buildings and Structure hitboxes and scaling fixed](https://github.com/UQdeco2800/2022-studio-3/issues/89)
- [ ] [Internal map representation](https://github.com/UQdeco2800/2022-studio-3/issues/83) to register entity with map
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] All buildings spawned in (Sep 9)
- [ ] Register with map component (Sep. 10)
 
**Completion Deadline:** Sep 10
 
# **Documentation**
- [Main description of feature](../wiki/Buildings-Functionality)
 
# **Member**
- Hugh Drummond (@hugh5)
