### ISSUE TITLE
Team 7 - Sprint 2 - Weather Effect Visual Design and Animation

### ISSUE THREAD

**Issue by Corfliss** [UQdeco2800/2022-studio-3#91]
# **Description**
**Task:** Weather Effect Visual Design and Animation
**Feature:** [Random Event Generator Continued](#92)

Weather effect requires visual design and animation, and we need the asset for those ideas. Hence, this ticket was made.
 
## **Example**
- Making the sprite for thunderstorm weather effect that covers the screen such as rainy sprite animation
- Making the sprite for cloudy animation such as cloud shadow in the ground.

# **Dependencies**
There is no dependency for this ticket.
 
# **Milestones**
- [x] Design the weather filter for the game
- [x] Make sprites for the weather effect in the game area in transparent background
- [x] Animate the sprite
 
**Completion Deadline:** Sep 6
 
# **Documentation**
To be added soon.
 
# **Member**
To be added soon.
