### ISSUE TITLE
Team 7 - Sprint 2 - Random Event Generator Continued

### ISSUE THREAD

**Issue by Corfliss** [UQdeco2800/2022-studio-3#92]
# **Description**
After sprint 1, our next sprint will be focusing on the weather representation using the random event generator feature that we already built. This includes representing the visual of the weather and the weather effects to the units movement. We also trying to implement our random feature to be implemented on other feature such as randomizing attack damage, and implementing map flooding speed randomization.

Implement a random event generator feature, which the name suggests, is about making events that might be helpful to players or not. We do this to add unpredictability to the game in order to make it more engaging. For example, like how a feature in the game such as building is damaged due to flooding and unable to operate, or if there is a person who needs help from the sinking place. In the final product, it will be making a procedurally-generated event that will advantage or disadvantage the player while also keeping the game balanced.

## SubFeature/component
* Weather visual representation
* Weather effect to unit movement

## **Examples (optional)**
* When the weather is thunderstorm, lighting effect might change to dark and will appear some flash animation in the screen.
* When the weather's snowy, it might be possible to adjust the player's movement speed so that the player's speed is related to the weather.
* Random value between 20-30 when attacking an unit.
* Some area will flood faster than the others.
*  Randomize the attack damage
* Implement the map flooding speed randomization
* (Optional) Evasion mechanics

# **Dependencies**
* #6
* #80

# **Milestones**
- [x] Make the design for the weather visual representation
- [x] Make the code for the weather visual representation
- [x] Make the code for the weather effect to unit movement

**Completion Deadline:**
Sep. 12

# **Extras**
- The dodge mechanic is the extra in case we already implement all of the features needed.

# **Documentation**
No documentation is required for now until the feature is completed.

# **Members**
- Junyao Li (@lijunyao1) (Junyao Li)
- Fauzan Hanandito Chaidir (@Corfliss)
- Quoc Dat Mai (@quocdat402) (Dat Mai)
- Haozhe Ding (@RichardD02) (Haozhe Ding)
- Jordan Brewis Foulger (@jordanlbf)
