### ISSUE TITLE
Team 9 - Stats balancing for each of the units and damage calculation (Soldiers)

### ISSUE THREAD

**Issue by Harqua** [UQdeco2800/2022-studio-3#93]
# **Description**
**Task:** Creating stats for each unit in the form of numbers and ensuring that they are balanced, so each of no unit is too broken
**Feature:** This contributes to any units, especially Soldiers and effectively ensures they match the Enemy units. Worker units will possibly have some of the stats implemented on them depending on how the game will work (#8, #12, #5 )

Different stats will be implemented to every unique unit depending on their abilities and weaknesses.

## **Examples**
-**Archer**: This unit could have big attack stats, but very low defense stats. They might be able to move very quickly to get into position and shoot enemies from far away.
-**Hoplites**: This units might have extremely high defense stats and decent range, but low attack and speed.

# **Dependencies**
This task is dependent on matching the stats with the opposing troops (Enemy) (see #12 ), and might need to be implemented in other friendly units as well(see #5)
 
# **Milestones**
The list of stats that needs to be applied to the units.
- [x] HP (Health Points): The unit dies when this goes to 0.
- [x] ATK (Attack Points): The amount of damage dealt scales accordingly with this stat.
- [x] DEF (Defense Points): The amount of damage received is reduced accordingly with this stat.
- [ ] SPD (Speed Points): The higher this stat is, the faster a unit can move.
- [ ] Range: The number of tiles that the unit can reach to hit the opposing units.

Optional stats:
- [ ] AFF (Affinity Points): The chance of a unit might trigger a critical attack.
- [ ] CRT (Crit Damage Points): The amount of damage increased to the original attack when a critical attack occurs.

Soldier units:
- [x] Archer
- [x] Swordsman
- [x] Spearman
- [x] Hoplites

# **Documentation**
- [Units Home](https://github.com/UQdeco2800/2022-studio-3/wiki/Units-Home)
 
# **Member**
- Garryco Thandi (Harqua)

**Comment by nhVietS** [comment]
Closed due to the finished of last sprint, this work has been take over by other teams
