### ISSUE TITLE
Team1 - Sprint 2 -Dynamic Status

### ISSUE THREAD

**Issue by jiupinbaocha** [UQdeco2800/2022-studio-3#94]
# **Description**
**Task:** Dynamic Status.
**Feature:** To be added(Our Feature ticket)

We will create the dynamic status with the Information and attributes according to units.
There will also be design iterations on information such as the properties of the unit.
Possibly using chromatic aberration and Gestalt principles to give dynamically changing visuals.
This function will be positioned on the right side of the information box to replace the text description of the original design.
 
## **Example**

- **HP bar**:  When units health value floats, the progress bar of health percentage will dynamicly float.

![image](https://user-images.githubusercontent.com/88020895/188075653-62222453-ed65-47f6-bd5f-4889a82d2339.png)

# **Dependencies**

- [ ] Unit Selection & Information Box (#5)
- [ ] Friendly Units (Worker) (#5)
- [ ] Friendly Units (Soldier) (#8)
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Design the layout of status
- [ ] Find a way to dynamic show the status by text & implement this
- [ ] Find a way to dynamic operation of the status bar
 
**Completion Deadline:** Sep.13

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- To be decided
