### ISSUE TITLE
Intro Song, Atlantis Theme Song, SoundFx of Friendly Unit

### ISSUE THREAD

**Issue by nhVietS** [UQdeco2800/2022-studio-3#95]
# **Description**
**Task:** [Remake Intro Song, Create Atlantis Theme Song, SoundFx of Friendly Units].
**Feature:** [Team 9 sprint 2: Soldiers feature continued](#86)

This task ticket will do the composing of the intro song and in-game music to match the game theme(Atlantis) using Chrome Music Lab and LMMS sound editing software. Create User Test by getting feedback of other members in studio class. Writing Wiki Page of Inspirations of music, how to use the software and step-by-step of composing the song. Collaborate with other teams to integrate the sound effect to the game.

# **Dependencies**
- [x] Mute Button in Team 5 - MainMenuScreen (#87) ( Abandoned due to team 5 will handle this task)
- [x] Soldier Attack Animation in Team 9 (#86)
- [x] Worker Mining Animation in Team 8 (#...) ( Abandoned due to team 8 will handle this task)
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Create another version of intro music (Sep 2)
- [x] Create sound effect of friendly units (Sep 12)
- [x] Compose draft of background music (Sep 10)
- [x] Do user test of the music, sound effect (Sep 11)
- [x] Edit and Release final draft of music, sound effect base on User test (Sep 12)
- [x] Integrate assets of music and sound to code (Sep 12)
 
**Completion Deadline:** Sept. 12
 
# **Documentation**
- [Main description of feature](../wiki/Feature)
 
# **Member**
- Hoang Viet Nguyen (@nhVietS) Hoang Viet Nguyen

**Comment by nhVietS** [comment]
[Atlantis Theme Song on Drive](https://drive.google.com/file/d/1KF69X0l8_8Y_NYkZwnAQN0mJoFX71xcf/view?usp=sharing)
This audio will play after you click on the start button. No looping recursively.
Please feel free to add your comments(raw data would be great), some of sample review questions:
- Do you think the music will match the game theme?
- Do you think the tempo(beat per minute) is ease to listen?
- Do you think the shifting between the audio in soundtrack smooth?
- Any other comments are wellcome.

**Comment by Harqua** [comment]
The transition at the end might sound a little bit weird, but other than that, the song builds the tense and might be suitable for the theme of our game as the Atlanteans are trying to defend their home country. BPM is pretty neat as well.

**Comment by quocdat402** [comment]
sounds decent but personally i don't think the drum kick is necessary for the theme song since it doesn't fit the atlantis theme overall.

**Comment by alyshaziya** [comment]
The music matches the overall game theme, the tempo is nice and it builds the tension of the game well and it also fits nicely with the home screen art style. The only thing id probably change is the ending transition as it changes the mood and drops out suddenly

**Comment by Corfliss** [comment]
The overall sound brings the atmoshpere together, perhaps you can improve it by making a loopable version of it, and also probably tweaking the ending of the song so that it doesn't sound a little bit abrupt.

**Comment by yobicakes** [comment]
The music goes a great job at tying the game together and provides a mysterious, almost cynical surround to the game. This music won't just fit in with the main menu but may also help establish the cutscenes in a more serious context. In the context of the main menu screen, I would agree that this music may need to be loopable (without a fade-out at the end). Otherwise, the overall tone was great!

**Comment by nhVietS** [comment]
In general, the final draft of in-game music would less drum kick or distracted sound; extend the ending should help it easier to listen.
Here the [link to Drive of final draft](https://drive.google.com/file/d/11bBOdigSQkQ2rZYYU2AXbPOGe_Dm3ATc/view?usp=sharing)
