### ISSUE TITLE
Team 1 - Sprint 2 - the appearance of Information Box

### ISSUE THREAD

**Issue by jiupinbaocha** [UQdeco2800/2022-studio-3#96]
# **Description**
**Task:** the appearance of Information Box
**Feature:** [Unit Selection Display/UI](#2)

In the last round user testing, more than 40% of respondents said they didn't think the infobox should always be displayed in the bottom left of the screen, which obscures some space.
In response to this feedback, we will re-iterate the infobox representation and leave it hidden under normal circumstances. Whenever the user selects a unit or switches to another unit, the infobox appears with the required information. Whenever the selection behavior ends, the infobox disappears again.

In addition, there will be a series of emphasis on the performance content in the infobox. In the to-do column on the right, we are suggested to pre-design icons and text descriptions that express properties. They will be combined with pure text data to improve the overall look and feel.
 
# **Example**
- **Buildings**: The box in this image only shown while user comfirm to select any units, and hide anytime else.

- **Soilders**: The icon/progress bar for soilder's status will designed(e.g. ATK,DEF,speed). The apperance of status should like:

- -  _(Status Icon) && (Status Name) && (Status Value)_

# **Dependencies**
- [ ] Friendly Units (Worker) (#5 )
- [ ] Friendly Units (Soldier) (#8 )
- [ ] Buildings  (#19 )
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Test current box generation
- [ ] Find a functional listener to hide/show the box
- [ ] Start Unit test/ User testing to check its performance

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
To be decided

**Comment by Sourav-RC** [comment]
Done
