### ISSUE TITLE
Team 6 - Map Tile Graphic Design

### ISSUE THREAD

**Issue by MaxJenko** [UQdeco2800/2022-studio-3#97]
# **Description**
**Task:** Map Tile Graphic Design(#3).
**Feature:** [Team 6 Sprint 2 - Map Design](#2)

It is essential that the tiles created flow well together and are pleasing to look at. After group collaboration regarding the previous map tile designs, refinements were implemented. At this stage, some tiles can be static (e.g. grass and sand) while others would look significantly better if they were animated. Through the use of an atlas file, multiple variations of a tile can be created and the game will cycle through them, giving the impression that they are moving. I am also working on User Test questions that can be used to survey students about the game's current display.
 
## **Example**
- **Map Component**: The grass and sand tiles will be static while the ocean will be animated

# **Dependencies**
Initial drafts of the grass, sand and ocean tiles
Style of Fengqi Yu's wave tile so that the ocean and wave's border is seamless
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 Create a new grass tile (Aug. 30)
- [x] Step 2 Create a new sand tile (Sep. 6)
- [x] Step 3 Create a new ocean tile (Sep. 13)
- [x] Step 4 Finalise User Test Questions (Sep. 13)
 
**Completion Deadline:** Sep. 13
 
# **Documentation**
- Uploading finished products to the group discord for team recommendations

# **Member**
- Max Jenkins (@MaxJenko)
