### ISSUE TITLE
Team 8 - Sprint 2 - Friendly Worker Units Continued

### ISSUE THREAD

**Issue by HaroldHS** [UQdeco2800/2022-studio-3#98]
# **Description**

This feature ticket is the continuation of the previsous [ticket](https://github.com/UQdeco2800/2022-studio-3/issues/5). We will create the **worker units** which are apart of a larger set of **friendly** units that the player can control and assign to do tasks throughout the duration of the game. More specifically, worker units will allow the player to collect resources, and build or repair player structures, which is a core gameplay feature within RTS games.

## SubFeature/component
- Unit selection - worker units should be selectable and de-selectable by the player
- Path finding - worker units should be able to find a path between point A and point B, which avoids other entities
- Unit movement - selected worker units should be able to move to an unobstructed location specified by the player
- Task system - worker units should be able to perform tasks when prompted by the player
- Forager - a specialisation of the worker unit which scours the map for resources that can be harvested for wood
- Miner - a specialisation of the worker unit which collects stone and iron resources
- Builder - a specialisation of the worker unit which can construct dams to slow flooding, and repair structures
- Sprites - pixel-art designs for each of the unit-types listed above

# **Dependencies**

- Path finding logic will depend on the map layout, and how entities/objects are stored for the map  - #3
- Unit selection will be a multi-team task - #2 and #10

# **Milestones**

- [ ] #16  (Saturday, Week 7)
- [ ] Added a means of moving selected worker units (Saturday, Week 7)
- [ ] #25 (Tuesday, Week 7)
- [ ] #13 (Wednesday, Week 7)
- [ ] #22 (Friday, Week 7)
- [ ] #23 (Friday, Week 7)
- [ ] #20 (Friday, Week 7)
- [ ] Designed sprites for worker units (Tuesday, Week 7)

**Completion Deadline:** Sept. 11 - Monday, Week 8 (prior to the completion of Sprint 2)

# **Extras**
- [ ] Worker units flee from approaching enemy units

# **Documentation**
Pages will be added to the game wiki detailing the feature

# **Members**
- Lorenzo (@lorenzopolicar) (Lorenzo Policar)
- Harold (@HaroldHS) (Harold Hotma Sibuea)
- Wishnu (@hazlazuardi) (Wishnu Hazmi Lazuardi)
- Yash (@yashvardhanbatra) (Yashvardhan Batra)
