### ISSUE TITLE
Team 2 Sprint 2 Advanced Buildings

### ISSUE THREAD

**Issue by Spooey** [UQdeco2800/2022-studio-3#99]
# **Description**
This feature involves spawning all the buildings and structures into the city in the map so the player has somewhere to explore and buildings to interact with. The scaling of buildings and structure need to be coherent (e.g. townhall should be bigger than barracks and buildings should be bigger then the player). The hitboxes also need to be configured so they are representative of the sprite.
This feature also includes the UI development for buildings so the player can interact with the features the building provides.
We also plan to make new sprites and animations for buildings and their leveled up design. 

## SubFeature/component (optional)
If the ticket contains multiple components, you should explain them in more detail here.
Design features
  Level up design for barracks
  Level up design for townhall
  Level up design for walls
  Animations for barracks
  Animations for townhall
  Animations for walls
  Path design
  Level up button UI design
  Barracks button UI design
  Townhall UI design

Code 
- Building UI (level up, health)
- Barracks UI
- Townhall UI
- Barracks spawns units
- Barracks Level up
- Townhall level up
- Wall level up
- Buildings spawn layout in city
- Structures spawn layout in city

## **Examples (optional)**
- **Part/Feature**: Depending on the ticket, you will often want to provide some examples of how it would play out in the game. See next point for example...
- **map seed**: maps can be generated from a "seed" where there may be different attributes, e.g. island, mainland, etc.
# **Dependencies**
- All specific building UI will be completed after the generic level up/health UI
- UI will depend on the completion of the button designs

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Goal 1 (Sep. 6): Building layout completed in game, level up/health UI.
- [ ] Goal 2 (Sep. 12): UI buttons work for leveling up and the specific button for that building. Animations implemented in game.

**Completion Deadline:** Sep. 13

# **Extras (optional)**
- [ ] Extra components that you may implement if you get time.
- [ ] ...

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- - UI guide and button features
- User documentation

# **Members**
- Hugh Drummond (@hugh5)
- Sylvia Chen (@syl2211)
- Wenfeng Wang(@WW7796332)
- Angus Buchanan (@Spooey)
- Wenjing Shan(@nicococole)
